### ISSUE TITLE
Python 3.5 on Ubuntu 16.04

### ISSUE THREAD

**Issue by thorade** [mcmtroffaes/sphinxcontrib-bibtex#100]
Ubuntu 16.04 defaults to Python 3.5, but there seems to be no 3.5 package on PyPi:
https://pypi.python.org/pypi/sphinxcontrib-bibtex

```
pip install -U spinxcontrib-bibtex
Collecting spinxcontrib-bibtex
Could not find a version that satisfies the requirement spinxcontrib-bibtex (from versions: )
No matching distribution found for spinxcontrib-bibtex
```
Would it be difficult to add a Python 3.5 version?

**Comment by mcmtroffaes** [comment]
Yes it's already in develop - I'll push a new release.

**Comment by thorade** [comment]
Thanks a lot, this will help me with cross testing Python 2 versus 3, and Windows versus Linux.

**Comment by mcmtroffaes** [comment]
New version on pypi. Thanks again for reporting!

**Comment by thorade** [comment]
I don't know why, but installation on Xubuntu 16.04 still fails:
```
mthorade@Xubuntu1604:~$ pip --no-cache-dir install spinxcontrib-bibtex
Collecting spinxcontrib-bibtex
  Could not find a version that satisfies the requirement spinxcontrib-bibtex (from versions: )
No matching distribution found for spinxcontrib-bibtex
```
For now, I'll just use it on Windows.

**Comment by mcmtroffaes** [comment]
Strange. I tested in a pure nix shell with just python 3.5, it definitely works for me...

**Comment by thorade** [comment]
Sorry for the confusion, I had a typo in the command all the time (spinx instead of sphinx).
Now it works. Thanks again for your time.

**Comment by mcmtroffaes** [comment]
Great! You're welcome, thanks once more for reporting!
