### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by agjohnson** [mcmtroffaes/sphinxcontrib-bibtex#102]
I'm seeing large memory usage on docs with a large bibliography file. Memory usage continues to balloon after parsing completes on the bibliography file -- memory usage peaks around 7.5G

This seems like leaky behavior to me, though I haven't had much luck tracking things down with `gdb`. I'm also not familiar enough with bibtex to say that this isn't normal behavior, though that seems unlikely.

**Edit: found a hack fix and the likely cause, but not sure of the proper fix**

I was able to get a full pass of the doc build in when I truncated the bibliography to <100 entries -- it looks like excessive copying is the issue:
https://gist.github.com/agjohnson/c1ebef16c11d8d22204af9f7edd77c85#file-bibtex-profile-L28-L34

Inspecting the `pybtex.database.Entry` object, it has a copy of the original bibliography entries (!!). This explains the egregious memory consumption. The hack fix to reduce memory usage and parse the full list was to null out `entry.collection` before it was copied here:
https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/develop/sphinxcontrib/bibtex/cache.py#L312-L314

I didn't test what side-effects this had.

**Comment by mcmtroffaes** [comment]
Many thanks for the report and for tracking down the leak, much appreciated! I guess that something must have changed in pybtex for each entry now to have a reference to the full collection. For now we can fix the problem as you suggest. I will try to chase this up with pybtex to see if the reference to the collection can be removed, it seems a bit odd to have it in there.

**Comment by mcmtroffaes** [comment]
The collection is required for pybtex to resolve cross references. For now can you check whether the above patch fixes the problem for you? I'll need to add some tests involving cross references too to ensure everything works as it should.
