### ISSUE TITLE
Author name abbreviation

### ISSUE THREAD

**Issue by thorade** [mcmtroffaes/sphinxcontrib-bibtex#105]
When running the Sphinx example/test:
https://github.com/mcmtroffaes/sphinxcontrib-bibtex/tree/develop/test/sphinx
most author names are abbreviated as expected, but not all, especially not
```
@ARTICLE{Astrom2005,
  author = {{\AA}str{\"o}m, Karl J. and Klein, Richard E. and Lennartsson, Anders},
```
With some small changes it is abbreviated:
```
@ARTICLE{Astrom2005,
  author = {Astr\"om, Karl J. and Klein, Richard E. and Lennartsson, Anders},
```
So, using `\"o` is acceptable, but using `{\"o}` breaks the abbreviation.
I can fix this on my side, but I do not know what to do about the `{\AA}`.
Any suggestions? Thanks.

**Comment by thorade** [comment]
Here is another example that breaks the abbreviation: O'Donnel
```
@inproceedings{odonnell_simmodel:_2011,
  address = {Sydney, Australia},
  title = {{SimModel}: {A} domain data model for whole building energy simulation},
  booktitle = {{IBPSA} {Building} {Simulation} 2011. {Sydney}, {Australia}},
  publisher = {IBPSA},
  author = {O'Donnell, James T. and See, Richard and Maile, Tobias and Bazjanac, Vladimir and Haves, Philip},
  year = {2011}
}
```

**Comment by thorade** [comment]
Yet another example:
The entry
```
@InBook{Kristensen83,
  author = 	 {B. B. Kristensen and Ole L. Madsen and B. M{\o}ller-Pedersen and K. Nygaard},
```
is abbreviated as [AKMMllerPN83], but when I change it to
```
@InBook{Kristensen83,
  author = 	 {B. B. Kristensen and Ole L. Madsen and B. Moller-Pedersen and K. Nygaard},
```
it is abbreviated as [AKMMPN83] but of course the ø is then an o.

**Comment by Jellby** [comment]
I think this may be related to [this bug in pybtex](https://bitbucket.org/pybtex-devs/pybtex/issues/98/name-parsing-gets-confused-when-a-part-of).

**Comment by thorade** [comment]
Closing for now, as it seems to be a pybtex issue.
