### ISSUE TITLE
Many hundrests of reference breaks label generation

### ISSUE THREAD

**Issue by laszewsk** [mcmtroffaes/sphinxcontrib-bibtex#110]
For some reason we see that the label generator breaks if we have many hundrets of refernces on the same page.

We see that the lables will includes charaters such as

\ | { } 

Naturally this does not work in latex. I am not yet sure of the origin to this problem. Our lables look like www-keyword for all of our refernces. and after a particular number we see in the sphinx generated file that it tries to build invalid refernces: Here an example for the generated latex file

at the place where we call it we get 

jclouds \phantomsection\label{\detokenize{i524/technologies:id177}}{\hyperref[\detokenize{i524/technologies:www-jclouds}]{\sphinxcrossref{{[}www\{{]}}}} is a java based

at the bibitem we get

\bibitem[www\{]{\detokenize{www_}}{\phantomsection\label{\detokenize{i524/technologies:www-jclouds}} 
JClouds, components. Web Page. Accessed: 2017-01-20. URL: \url{https://jclouds.apache.org/}.
}

in our bibtex file we have

@Misc{www-jclouds,
  Title                    = {{JClouds}, components},
  HowPublished             = {Web Page},
  Note                     = {Accessed: 2017-01-20},
  Owner                    = {S17-IO-3005},
  Url                      = {https://jclouds.apache.org/}
}

**Comment by mcmtroffaes** [comment]
Looks like you got this fixed. Thanks for reporting anyway!
