### ISSUE TITLE
Compilation issues with Sphinxcontrib-bibtex

### ISSUE THREAD

**Issue by mattberjon** [mcmtroffaes/sphinxcontrib-bibtex#113]
Hi,

I'm having issues with the compilation of my project using sphinxcontrib-bibtex. Basically, the compilation never compile the bibliography the first time. I have errors of the type `citation not found` on several citations even if it seems that my bibtex file seems fine. Even stranger, I need to modify the `conf.py` file in Sphinx, in order to force another compilation that end-up with a successful compilation including the bibliography. At first I thought it was related to ReadTheDocs. Unfortunately, the problem seems somewhere else, that's why I'm asking some help here.

For people who would like to give it a try, I would

- issue open on ReadTheDoc project: rtfd/readthedocs.org#2601
- My project having the issue on Github: [Auditory Motion Perception][l1]
- A build on read the docs: [#4923632][l2]

I can provide as well the output locally as I have the same issue if people are interested in.

[l1]: https://github.com/mattberjon/auditory-motion-perception
[l2]: https://readthedocs.org/projects/auditory-motion-perception/builds/4923632/

**Comment by mcmtroffaes** [comment]
Did the branch fix it for you?

**Comment by mattberjon** [comment]
@mcmtroffaes so sorry for the late reply, I changed country and didn't get much time lately. It works perfectly, sorry for not seeing the workaround in the documentation.
