### ISSUE TITLE
Mathmode support

### ISSUE THREAD

**Issue by blechta** [mcmtroffaes/sphinxcontrib-bibtex#114]
I'm not sure to which extent this is `sphinxcontrib-bibtex` issue but it would be nice to support mathmode in bibliography entries. To reproduce the current behaviour, use this patch
```
diff --git a/test/latex_refs/test.bib b/test/latex_refs/test.bib
index 2bcab4a..b5879fa 100644
--- a/test/latex_refs/test.bib
+++ b/test/latex_refs/test.bib
@@ -1,6 +1,6 @@
 @InCollection{1657:huygens,
   author =      {Christiaan Huygens},
-  title =       {De Ratiociniis in Ludo Ale{\ae}},
+  title =       {De Ratiociniis in Ludo Ale{\ae} $\pi = 3$},
   booktitle =   {Exercitationum Mathematicarum Libri Quinque: Quibus accedit {C}hristiani {H}ugenii Tractatus de Ratiociniis in Ale{\ae} Ludo},
   pages =       {517--524},
   publisher = {Ex officina Johannis Elsevirii},
```

and run
```
cd test/latex_refs
sphinx-build -M latex "." "_build"
grep \\$ _build/latex/test.tex
```

The output is
```
Christiaan Huygens. De ratiociniis in ludo aleæ \$\textbackslash{}pi = 3\$. In Franciscus á Schooten, editor, \sphinxstyleemphasis{Exercitationum Mathematicarum Libri Quinque: Quibus accedit Christiani Hugenii Tractatus de Ratiociniis in Aleæ Ludo}, pages 517\textendash{}524. Ex officina Johannis Elsevirii, Lugd. Batav., 1657.
```

Next step would be to on MathJax support in html output.

**Comment by mcmtroffaes** [comment]
Yes, latex processing in Pybtex is a bit limited and I don't think it supports MathJax. It would be nice if this extension could somehow leverage for instance http://www.sphinx-doc.org/en/stable/ext/math.html#module-sphinx.ext.mathjax ...

**Comment by mcmtroffaes** [comment]
Pybtex now handles all latex formatting, so I think this can be closed.

**Comment by blechta** [comment]
That's weird. The MWE above still fails.

**Comment by mcmtroffaes** [comment]
I'm sure it does, but it's something that would be best addressed in pybtex's formatting engine directly (as that engine fully handles conversion to html; the extension is just a wrapper around pybtex).

**Comment by blechta** [comment]
Unfortunately, it is still quite a fluke. For instance, braces are not handled correctly. Bibtex with `$\pi = \frac{22}{7}$` results in HTML with `$\pi = \frac 227$`.

**Comment by mcmtroffaes** [comment]
Please discuss with pybtex upstream to see how this formatting can be improved. If pybtex can generate the correct html, then sphinxcontrib-bibtex will too. The problem is that doing this completely correctly requires a full LaTeX parser, and I doubt pybtex would ever be able to support all of LaTeX. Currently it uses latexcodec to support simple formatting (for instance, something like $\pi$ should work just fine).

My recommendation is to stick to unicode for bibtex, where possible, when used with pybtex.
