### ISSUE TITLE
warning about Directive

### ISSUE THREAD

**Issue by ndarmage** [mcmtroffaes/sphinxcontrib-bibtex#115]
Noticed after moving to sphinx >= 1.6.1

.. code-block::
  
  RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 
  1.7, please use the standard library version instead.
    from sphinx.util.compat import Directive

In directives.py, remove the line:
from sphinx.util.compat import Directive

and import Directive too from docutils as:
from docutils.parsers.rst import Directive, directives

**Comment by mcmtroffaes** [comment]
Thanks for reporting. I've got a patch for this but unfortunately travis fails... I'll need some time to get to the bottom of these failures.

**Comment by mcmtroffaes** [comment]
Fixed. Thanks for reporting, and apologies for the slow response!
