### ISSUE TITLE
Reference not found when author/year/title are duplicate

### ISSUE THREAD

**Issue by Jellby** [mcmtroffaes/sphinxcontrib-bibtex#117]
I was testing something else and created a bogus .bib file where I just copied the same item twice, changing its label. Then I cite the two labels in the text (default style) and I got `WARNING: citation not found: ECP:10`. It turns out if I modify the author, title or year (but not volume, page or other elements) this is solved. I guess this has to do with automatic label generation, probably in pybtex, but it should be possible to have bibliography items with same author/year/title and different bibtex labels.

**Comment by mcmtroffaes** [comment]
Hmmm, sounds like a rare corner case not covered by either sphinx or pybtex. :-/ Not sure I can do much about this within the extension itself.
