### ISSUE TITLE
Using latexcodec in sphinxcontrib-bibtex is no longer necessary

### ISSUE THREAD

**Issue by erosennin** [mcmtroffaes/sphinxcontrib-bibtex#127]
Hi,

sphinxcontrib-bibtex [implicitly uses latexcodec](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/8f72f9897a0324c797b742c551be3d263abb1e2a/sphinxcontrib/bibtex/directives.py#L122) to decode `.bib` files. This is no longer necessary, because Pybtex already uses latexcodec internally since version 0.20.

Doing the decoding on the Pybtex side allows to decode the contents of individual entry fields instead of decoding the whole `.bib` file. This is generally more robust and fixes some parsing problems.

Please just pass the docutils' `input_encoding` without the `"latex+"` prefix to `bibtex.Parser()`.

Thanks!

**Comment by erosennin** [comment]
Pybtex also handles curly braces since version 0.20, should be safe to remove `transform_curly_bracket_strip()` too.

**Comment by mcmtroffaes** [comment]
Oh, many thanks for that! That will indeed be more robust. Work on removal of latexcodec can be followed on this pull request: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/pull/129
