### ISSUE TITLE
feature request: nocite

### ISSUE THREAD

**Issue by abchenson** [mcmtroffaes/sphinxcontrib-bibtex#131]
It would be very useful to me to have something like the LaTeX \nocite{bibtexid} which does the same thing as cite (adds 'bibtexid' to the bibliography) without making a citation like '[13]' appear as it would with \cite.  Not sure how this should worked with your :cited: and :notcited: categories but in the default case it's clear what it should do.  If not is there a workaround for this?  Many thanks for your work on this project!

**Comment by abchenson** [comment]
Discovered a workaround for this:
in the rst 
```
.. container:: nocite
    :cite:`a-Almgren2003-an,a-Almgren2005-bc,a-Chen2002-lk,a-Lillo2003-ji,a-Engle2008-wz,a-Moro2009-by,a-Toth2011-ku,a-Mastromatteo2014-sy,a-Brokmann2014-qw,a-Bacry2014-ie`.
```
and in the theme css (so you have to have a custom them)

```
.nocite {
    font-size: 0;
}
```

**Comment by abchenson** [comment]
I found a work-around for this.  It would still be nice to have as a built-in feature (you have to have a custom style to get my solution to work for one thing).  In the rst you need:
```
.. rst-class:: hidden

:cite:`key`
```
in the theme style css you need
```
.hidden {
    display: none;
}
```

**Comment by mcmtroffaes** [comment]
You can already do this through the filtering system, see https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#filtering, but yeah, a nocite command that virtually adds a document to the cited category would make sense.
