### ISSUE TITLE
EOFError when trying -j option

### ISSUE THREAD

**Issue by abchenson** [mcmtroffaes/sphinxcontrib-bibtex#132]
Subject: EOFError when trying -j option

### Problem
- a project that otherwise build fine failed when trying the -j option
```
waiting for workers...

Exception occurred:
  File "/home/joe-h/miniconda3/envs/bmll-docs/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

```
Fails in sphinxcontrib.bibtex (see log)

#### Procedure to reproduce the problem
```
sphinx-build -j 4 docs docs/_build/html
```

#### Error logs / results

[sphinx-err-h4qv9xv1.log](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/files/1685716/sphinx-err-h4qv9xv1.log)

### Environment info
- OS: Linux
- Python version: 3.5
- Sphinx (1.4.8)
- sphinxcontrib-bibtex (0.3.6)

**Comment by abchenson** [comment]
works after upgraded sphinx to 1.6.6

**Comment by mcmtroffaes** [comment]
Ok, I think this can be closed then. Thanks for reporting anyway!
