### ISSUE TITLE
Unresolved Citations Across Documents

### ISSUE THREAD

**Issue by abchenson** [mcmtroffaes/sphinxcontrib-bibtex#134]
https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#known-issues-and-workarounds

This issue is mentioned in the docs: citations across many files are only resolved if the bibliography directive is processed after everything else.  In my build I have to call the file zzz_references.rst for example. Are there any plans to correct this?

**Comment by mcmtroffaes** [comment]
This is inherently an issue with the way sphinx is designed to deal with citations. I'm not aware of any plans upstream to improve the handling of citations across documents. I'm not sure how it could be easily achieved in the plugin itself. I'm sorry that I can't be more helpful!

**Comment by skirpichev** [comment]
@mcmtroffaes, I [asked](https://github.com/sphinx-doc/sphinx/issues/5940) sphinx devs and they suggested using [event-env-check-consistency()](https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-env-check-consistency) to fix this issue.  Maybe it should be reopened?

**Comment by mcmtroffaes** [comment]
I just noticed I never responded to this. My apologies. The event-env-check-consistency hook comes in too late in the process because at that time, docutils has already processed and resolved all references...
