### ISSUE TITLE
Osx 10.11.6 El Capitan - Help in installation

### ISSUE THREAD

**Issue by borisalmonacid** [mcmtroffaes/sphinxcontrib-bibtex#138]
Hello, I need help in the installation of sphinxcontrib-bibtex.
I tried in many ways, but I could not compile using the make command.

➜  thesis_source git:(master) ✗ make html
Running Sphinx v1.6.3
loading translations [es]... done
**Extension error:
Could not import extension sphinxcontrib.bibtex (exception: No module named oset)
make: *** [html] Error 1**

---
Osx 10.11.6 El Capitan
Sphinx                            1.7.4      
sphinxcontrib-bibtex      0.4.0      
sphinxcontrib-websupport  1.0.1
Python 2.7.10
Python 3.6.4

------
In conf.py file:

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinxcontrib.bibtex']

--------

➜  thesis_source git:(master) ✗ pip install sphinxcontrib-bibtex
Requirement already satisfied: sphinxcontrib-bibtex in /usr/local/lib/python3.6/site-packages (0.4.0)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.6/site-packages (from sphinxcontrib-bibtex) (1.10.0)
Requirement already satisfied: pybtex-docutils>=0.2.0 in /usr/local/lib/python3.6/site-packages (from sphinxcontrib-bibtex) (0.2.1)
Requirement already satisfied: pybtex>=0.20 in /usr/local/lib/python3.6/site-packages (from sphinxcontrib-bibtex) (0.21)
Requirement already satisfied: oset>=0.1.3 in /usr/local/lib/python3.6/site-packages (from sphinxcontrib-bibtex) (0.1.3)
Requirement already satisfied: Sphinx>=1.0 in /usr/local/lib/python3.6/site-packages (from sphinxcontrib-bibtex) (1.7.4)
Requirement already satisfied: docutils>=0.8 in /usr/local/lib/python3.6/site-packages (from pybtex-docutils>=0.2.0->sphinxcontrib-bibtex) (0.15b0.dev0)
Requirement already satisfied: PyYAML>=3.01 in /usr/local/lib/python3.6/site-packages (from pybtex>=0.20->sphinxcontrib-bibtex) (3.12)
Requirement already satisfied: latexcodec>=1.0.4 in /usr/local/lib/python3.6/site-packages (from pybtex>=0.20->sphinxcontrib-bibtex) (1.0.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from oset>=0.1.3->sphinxcontrib-bibtex) (38.5.2)
Requirement already satisfied: imagesize in /usr/local/lib/python3.6/site-packages (from Sphinx>=1.0->sphinxcontrib-bibtex) (1.0.0)
Requirement already satisfied: Pygments>=2.0 in /usr/local/lib/python3.6/site-packages (from Sphinx>=1.0->sphinxcontrib-bibtex) (2.2.0)
Requirement already satisfied: alabaster<0.8,>=0.7 in /usr/local/lib/python3.6/site-packages (from Sphinx>=1.0->sphinxcontrib-bibtex) (0.7.10)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.6/site-packages (from Sphinx>=1.0->sphinxcontrib-bibtex) (2.12.4)
Requirement already satisfied: babel!=2.0,>=1.3 in /usr/local/lib/python3.6/site-packages (from Sphinx>=1.0->sphinxcontrib-bibtex) (2.5.3)
Requirement already satisfied: Jinja2>=2.3 in /usr/local/lib/python3.6/site-packages (from Sphinx>=1.0->sphinxcontrib-bibtex) (2.10)
Requirement already satisfied: sphinxcontrib-websupport in /usr/local/lib/python3.6/site-packages (from Sphinx>=1.0->sphinxcontrib-bibtex) (1.0.1)
Requirement already satisfied: snowballstemmer>=1.1 in /usr/local/lib/python3.6/site-packages (from Sphinx>=1.0->sphinxcontrib-bibtex) (1.2.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from Sphinx>=1.0->sphinxcontrib-bibtex) (17.1)
Requirement already satisfied: pytz>=0a in /usr/local/lib/python3.6/site-packages (from babel!=2.0,>=1.3->Sphinx>=1.0->sphinxcontrib-bibtex) (2013.7)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/site-packages (from Jinja2>=2.3->Sphinx>=1.0->sphinxcontrib-bibtex) (1.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/site-packages (from packaging->Sphinx>=1.0->sphinxcontrib-bibtex) (2.2.0)

**Comment by mcmtroffaes** [comment]
The error says that you're missing oset, but oset is installed according to the logs. If I had to guess, you have multiple python installations, and your make call is using the wrong one. This is not an issue with sphinxcontrib-bibtex, but with your specific setup. I'd recommend running in a virtual environment to ensure that you have all the right things installed in the right place:

https://docs.python.org/3.6/library/venv.html
