### ISSUE TITLE
Question: Link for BibTeX citation for each entry

### ISSUE THREAD

**Issue by fietew** [mcmtroffaes/sphinxcontrib-bibtex#139]
In the displayed bibliography (html), I would like to have a link appended to each reference, where people can copy the original BiBTeX entry for citing the corresponding publication in their own LaTeX document. How could this be done?

One of my ideas was to generate separate .bib files for each reference during the building process and provide a static link to them in the bibliography. Is this sensible?

**Comment by mcmtroffaes** [comment]
It's a bit clunky, but you could simply include a url field that references a bib file for each reference.
