### ISSUE TITLE
Strange format of the generated bibliography list

### ISSUE THREAD

**Issue by weikang9009** [mcmtroffaes/sphinxcontrib-bibtex#140]
I am attempting to generate citations for our project using sphinx v1.7.5 [sphinx_bootstrap_theme "yeti"](https://bootswatch.com/yeti/). 
```
.. bibliography:: source/_static/references.bib
   :style: alpha
   :cited:
```
The rendering of the generated bibliography list seems a little odd:
![image](https://user-images.githubusercontent.com/7359284/42296258-7114511c-7fa8-11e8-81ee-84624247ad69.png)
Each entry of the bibliography is rendered as a table and the citation key is transparent. Not sure if this is due to the bootstrap theme "yeti" I am using as the same formatting happens when I switch to other bootstrap themes. 
If I change the type of list used for rendering the bibliography  to a bullet list. It renders just fine:
![image](https://user-images.githubusercontent.com/7359284/42296339-9402e9c6-7fa9-11e8-8ac3-d450cf0faea2.png)

**Comment by mcmtroffaes** [comment]
Yes, docutils renders citations as a table - this is expected. I know it doesn't line up nicely. That's a limitation of sphinx itself, in how it renders docutils citations. I'd guess that the transparency is a problem with the style that you are using. I'm sorry that I cannot be more helpful, but the way to fix the rendering is simply to edit the css appropriately.
