### ISSUE TITLE
question: is it possible to create custom entry types

### ISSUE THREAD

**Issue by abchenson** [mcmtroffaes/sphinxcontrib-bibtex#142]
The title says it all really: I see the way to edit the way that standard entries are displayed, but what if I want to introduce a new one, e.g. @patents is non-standard but fairly common.  This is possible in LaTeX, is it possible here?

Thanks in advance, the tool is working well for me in general.

**Comment by abchenson** [comment]
I worked out how to do this, I was looking at a different version of pybtex in bitbucket than the one that I have installed and that confused me.

**Comment by ukos-git** [comment]
I ran into the issue today that @patents are not supported. How did you solve it?

**Comment by mcmtroffaes** [comment]
I guess you should be able to add custom entry types by customizing the style. Here's a simple example (doesn't create a new entry but it does show you how to customize the style):

https://github.com/mcmtroffaes/sphinxcontrib-bibtex/tree/develop/test/custom_style

Does this help?
