### ISSUE TITLE
citations reused in multiple documents not showing up

### ISSUE THREAD

**Issue by jrobcary** [mcmtroffaes/sphinxcontrib-bibtex#144]
I have 5 documents, which I build individually as pdfs, and together (including them via a toctree) as html.  I include the bibliography in each of the individual documents, and the html works, with the bibliography showing up in the alphabetically last document.  But the individual (pdf) documents do not contain complete bibliographies.

Sometimes, for some of the pdfs, I can get the bibliography to show up by re-running sphinx-build, but for others this does not help.

It looks like I might use key prefixing (https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#section-key-prefixing) except that I need to use the same :cite: key for both the inclusive html document and the separate pdf document.  

Am I missing something?  Or is this not possible with sphinx-build?

**Comment by jrobcary** [comment]
An even simpler case

For the directory structure,

<pre>
Main.rst # contains :cite:`fubar`, includes zres.rst
  Adir/ABdir/AB.rst # contains :cite:`foo`
  Bdir/BBdir/BB.rst # contains :cite:`bar`
zres.rst # Contains bibliography:: common/com.bib
  common/com.bib
</pre>

Not all the citations to show up. It finds the citations in AB.rst, but then not in BB.rst or any later rst file. So in the above example, the endnotes, fubar and foo, show up but not the bar endnote.

**Comment by mcmtroffaes** [comment]
Sorry for being so silent on this. In a nutshell, I don't think sphinx-build has a notion of building a document through individual pdfs...
