### ISSUE TITLE
DOC: wrong explanation of encoding (`latex+latin`)

### ISSUE THREAD

**Issue by kmuehlbauer** [mcmtroffaes/sphinxcontrib-bibtex#145]
With  #129 latexcodec was removed from codebase but it's still mentioned in the docs.

**Comment by kmuehlbauer** [comment]
Suggested Patch: https://github.com/kmuehlbauer/sphinxcontrib-bibtex/tree/km-patch-1

**Comment by mcmtroffaes** [comment]
Thanks, I've merged https://github.com/kmuehlbauer/sphinxcontrib-bibtex/commit/f7000a47109115ed3d0aedc374b709a1e39f25b2 into develop now.
