### ISSUE TITLE
Deprecated app.info

### ISSUE THREAD

**Issue by Jellby** [mcmtroffaes/sphinxcontrib-bibtex#147]
I'm getting this message with sphinx 1.8.0:

```
updating environment: 121 added, 0 changed, 0 removed
/usr/local/lib/python2.7/dist-packages/sphinx/application.py:402: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.                                                             
  RemovedInSphinx20Warning)
checking for /OpenMolcas/doc/source/molcas.bib in bibtex cache... not found
```

and I think it comes from this extension. See http://www.sphinx-doc.org/en/master/extdev/logging.html

**Comment by thepith** [comment]
Note, that this error is not occurring on the current development branch. Install it using:
```
pip install git+https://github.com/mcmtroffaes/sphinxcontrib-bibtex.git
```

**Comment by mcmtroffaes** [comment]
Thanks for reporting. Fixed in https://github.com/mcmtroffaes/sphinxcontrib-bibtex/pull/152 (will merge into develop soon).
