### ISSUE TITLE
Bibliographystyle: IEEEtran

### ISSUE THREAD

**Issue by fleimgruber** [mcmtroffaes/sphinxcontrib-bibtex#148]
I am using the directive
```
.. bibliography:: the.bib
   :style: IEEEtran
```
on which pybtex chokes with
```
Exception occurred:
  File "C:\Users\user\AppData\Local\Continuum\miniconda3\envs\env\lib\site-packages\pybtex\plugin\__init__.py", line 80, in _load_entry_point
    raise PluginNotFound(group, name)
pybtex.plugin.PluginNotFound: plugin pybtex.style.formatting.IEEEtran not found
```

How can I debug this further?
I assumed pybtex to pick up .bst styles from the LaTeX installation and not it's own plugin mechanism?

**Comment by mcmtroffaes** [comment]
I'm afraid that you assume wrongly... You can only use pybtex styles (either preinstalled, or one that you write yourself).

**Comment by fleimgruber** [comment]
I was just wondering whether [this ](https://docs.pybtex.org/formats.html#bibliography-style-formats) section in the pybtex documentation is new? If pybtex supports regular BibTeX `.bst` files, what would be needed for sphinxcontrib-bibtex to make use of that?

**Comment by mcmtroffaes** [comment]
Sorry for not responding earlier. The bst styles are for generating latex only, however sphinx essentially generates docutils nodes, which are then used to generate html, latex, and so on. Because sphinx goes via docutils, the extension can only supports python styles.

**Comment by fleimgruber** [comment]
I see. Do you have recommendations about implementing the IEEEtran.bst style as a Python style? My gut feeling is that `pybtex.style.template` would be the way to go. I found the styles in https://bitbucket.org/pybtex-devs/pybtex/src/HEAD/pybtex/style/formatting, but maybe I should start from `BaseStyle` as well?

**Comment by mcmtroffaes** [comment]
That's a good question. I'd recommend starting from unsrt.py (most styles I've seen are derived from that style).
