### ISSUE TITLE
Sort references in the order they are cited

### ISSUE THREAD

**Issue by certik** [mcmtroffaes/sphinxcontrib-bibtex#15]
I am using your plugin to write my dissertation. I would like the numbering of the citations to start from [1] and continue as [2], [3], ..., in the order that I cite it in the text. Currently, the references are sorted in some way, and so in my case the citations start as [26], [23], [24], [32], [18], ...

Is there any way to fix this?

**Comment by Jellby** [comment]
Sphinx surely knows the order in which the documents should be displayed (with the "previous" and "next" links, or when generating a LaTeX/PDF document). Isn't this order somehow available for this extension to sort the bibliography?

**Comment by Jellby** [comment]
@mcmtroffaes For the record, this worked for me, but I guess it would fail with multiple bibliographies or if the bibliography is not in the last processed document:

in `cache.py`, at `get_all_cited_keys`, change the loop to:

    for docname in sorted(self._cited, key=lambda x: self.sortorder[x]):

In `transform.py` add a method in `BibliographyTransform`:

    def sortdocs(self):
        sortorder = {}
        env = self.document.settings.env
        rel = env.collect_relations()
        init = [i for i in rel if rel[i][1] is None][0]
        docname = init
        i = 0
        while (docname is not None):
            sortorder[docname] = i
            docname = rel[docname][2]
            i += 1
        return sortorder

and at `apply`, insert between `bibcache` and `entries`:

    env.bibtex_cache.sortorder = self.sortdocs()

Maybe this can be done with a sorting plugin for pybtex, but I don't know how to access the `environment` or the document name for each citation there.
