### ISSUE TITLE
References not showing up on readthedocs.io

### ISSUE THREAD

**Issue by pjmark** [mcmtroffaes/sphinxcontrib-bibtex#150]
Hi

Could you help me please with the references not showing on readthedocs.org despite that it works for my on my local computer.

When I look at the compilation on readthedocs.org it says it's already satisfied.

Any idea why all the references/citations are not showing up?  Instead of numbers in text I get the BibTeX labels.

Many thanks,
Pawel

**Comment by mcmtroffaes** [comment]
I'm deeply sorry, but this isn't the appropriate place to get support with readthedocs.org. That said, if it works locally, then likely it is an issue with your readthedocs configuration.
