### ISSUE TITLE
Putting LaTeX bibliography where it is defined (same as in HTML)?

### ISSUE THREAD

**Issue by mgeier** [mcmtroffaes/sphinxcontrib-bibtex#156]
I find it unfortunate that the LaTeX bibliography ends up at the end of the document, while in HTML output the bibliography/bibliographies end(s) up where it/they is/are defined.

Of course, as stated in the docs (https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#mismatch-between-output-of-html-and-latex-backends), this is a feature of Sphinx and not caused by *sphinxcontrib-bibtex*.

But has anyone ever tried to work around this?

I think this should be possible, but I'm not sure about a few details how this should be done ...

I've come up with a brute force (and quite ugly) work-around, which might serve as a basis for a proper implementation.

First, we have to disable `BibliographyTransform`. If we could change the Sphinx code, we could remove it here: https://github.com/sphinx-doc/sphinx/blob/v1.8.2/sphinx/builders/latex/__init__.py#L283

A bit less destructive, we can also monkey-patch it away, I did this in my `conf.py`:

```python
import docutils
import sphinx.builders.latex

class DummyTransform(docutils.transforms.Transform):

    default_priority = 0

    def apply(self):
        pass

sphinx.builders.latex.BibliographyTransform = DummyTransform
```

In a real implementation, we would of course have to find another way to disable this. And this should ideally not interfere with Sphinx native citations.

As a second and last step, I added a bit of raw LaTeX around the bibliography directive in a `.rst` source file:

```rst
References
----------

.. raw:: latex

    \begingroup
    \def\section#1#2{}
    \def\chapter#1#2{}
    \begin{thebibliography}{1234}

.. bibliography:: my-references.bib

.. raw:: latex

    \end{thebibliography}
    \endgroup
```

This works surprisingly well, but of course it would be nice to have this without all the ugly work-around stuff.

Any comments or further ideas?

**Comment by mcmtroffaes** [comment]
I appreciate that you're engaging with upstream about this, however, as modifying the latex writer in this manner can be done independently of bibtex support, I feel that the functionality that you are requesting really belongs in a separate plugin so that it can be used and maintained completely independently of sphinxcontrib-bibtex. The bibtex pluging is concerned purely with converting bibtex citations to docutils citations.

**Comment by mgeier** [comment]
Just for reference: https://github.com/sphinx-doc/sphinx/issues/5893

**Comment by mcmtroffaes** [comment]
Thanks for sharing!

**Comment by mgeier** [comment]
In recent Sphinx versions, my work-around from above doesn't quite work anymore, here's an updated version:

```python
import sphinx.builders.latex.transforms

class DummyTransform(sphinx.builders.latex.transforms.BibliographyTransform):

    def run(self, **kwargs):
        pass

sphinx.builders.latex.transforms.BibliographyTransform = DummyTransform
```

**Comment by mcmtroffaes** [comment]
Reopening to remind myself to add something about this to the documentation & along with a regression test.
