### ISSUE TITLE
How to run parallel build when sphinxcontrib.bibtex is used?

### ISSUE THREAD

**Issue by chan109** [mcmtroffaes/sphinxcontrib-bibtex#164]
My sphinx build take about 20mins to build on Linux. After adding -j auto flag, the time has decreased 4mins and it is great improvement in terms of profermance. However, some page created by the sphinxcontrib-bibtex has broken because sphinxcontrib-bibtex is not parallel safe

Is there any solution to walk around the problem, being able to run my sphinx build in parallel and use the sphinxconrib-bibtex as well.

**Comment by mcmtroffaes** [comment]
Not at the moment, I'm sorry...

**Comment by mcmtroffaes** [comment]
Quick update: this is more or less working now, and should be fixed for the 2.0.0 release. See #210 if you already would like to try it out.
