### ISSUE TITLE
phdthesis type

### ISSUE THREAD

**Issue by ukos-git** [mcmtroffaes/sphinxcontrib-bibtex#170]
I am using the type keyword in @phdthesis to customize the displayed name.

https://en.wikipedia.org/wiki/BibTeX#Field_types

The type keyword should be respected if present instead of defaulting to `PhD thesis` for this entry.

[pybtex defines this field](https://bitbucket.org/pybtex-devs/pybtex/src/4bb9a928bb15f701d5ad95979f6d81c2cc2554bf/examples/xampl.bib#lines-314:323)

**Comment by ukos-git** [comment]
I tried with the [`@masterthesis` field](https://bitbucket.org/pybtex-devs/pybtex/src/4bb9a928bb15f701d5ad95979f6d81c2cc2554bf/examples/xampl.bib#lines-208:224) but that issued a style error:

```console
parsing bibtex file citation.bib... parsed 435 entries

Exception occurred:
  File "~/.local/lib/python2.7/site-packages/pybtex/style/formatting/__init__.py", line 69, in format_entry
    format_method = getattr(self, "format_" + entry.type)
AttributeError: 'Style' object has no attribute 'format_masterthesis'
The full traceback has been saved in /tmp/sphinx-err-kAuNN9.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:23: html] Error 2
```

**Comment by mcmtroffaes** [comment]
It looks like the unsrt style of pybtex does not look at the type field for the phdthesis entry. I've quickly written a patch to fix this. Could you test it out?

https://bitbucket.org/pybtex-devs/pybtex/pull-requests/14/support-type-when-formatting-phdthesis/diff

**Comment by mcmtroffaes** [comment]
The change was merged upstream, so closing. Thanks again for reporting!
