### ISSUE TITLE
Examples in docs?

### ISSUE THREAD

**Issue by bdice** [mcmtroffaes/sphinxcontrib-bibtex#181]
Hi, I am interested in using this package. As a potential new user, I really want to see what the output might look like, perhaps with some example citations in this package's own documentation. Another alternative would be to link to some other packages' documentation that are already using this package as examples.

Let me know if you have ideas for how you'd like to add these examples, and I may be able to contribute a PR back!

**Comment by mcmtroffaes** [comment]
That's a good suggestion. I've added a minimal rendered example to the docs now. You can already see it here:

https://sphinxcontrib-bibtex.readthedocs.io/en/latest/quickstart.html#nel87
