### ISSUE TITLE
better local bibliographies

### ISSUE THREAD

**Issue by drammock** [mcmtroffaes/sphinxcontrib-bibtex#184]
As far as I can tell, this extension works with default settings only if the user abides by two constraints:

1. each citation occurs only once
2. the `.. bibliography::` directive is invoked only once

The project I'm working on ([MNE-Python](https://mne.tools/dev/)) does not follow either constraint: one paper is often cited several times in different files (in multiple docstrings or documentation pages), and our convention is to have a separate `.. bibliography::` for each documentation page where a paper is cited. So for example:

### tutorial_one.py

```
# ... :cite:`foo,bar` ...

...

# .. bibliography:: ../../references.bib
#     :style: unsrt
#
#     desired result:
#     [1] foo...
#     [2] bar...
```

### tutorial_two.py

```
# ... :cite:`qux,foo,baz` ...

...

# .. bibliography:: ../../references.bib
#     :style: unsrt
#
#     desired result:
#     [1] qux...
#     [2] foo...
#     [3] baz...
```

Currently, to support this use case, I have to add and `:keyprefix: a-` to every `.. bibliography::`, and add the key prefix to every citation, and use unique prefixes for each documentation page in which we cite anything. This is a prohibitive amount of work: we have more than 150 unique references, many of them are cited multiple times across files, and we have a lot of documentation pages, so keeping track of which key prefixes are in use is difficult.  Additionally, unless I also specify a `:labelprefix:` in each `.. bibliography::`, I get `WARNING duplicate label for keys a-whatever and b-whatever` at build time (which I can't just ignore, because our documentation CI elevates warnings to errors).

Would you be willing to include a "single-file mode" where references are always resolved locally within the file in which they occur, instead of being pooled across all files?  Or perhaps a `:local:` option that could be added to `bibliography::` that would cause it to only render references that were cited in the current file?

**Comment by drammock** [comment]
The more I think about this, the more I think that adding a `:local:` option to the `.. bibliography::` directive is the right way to go.  It nicely mirrors Sphinx's `:local:` option for `.. contents::` directives.

**Comment by mcmtroffaes** [comment]
Sadly, sphinx does not support local citations. However, footnotes are local. What I could see as a solution for your use case is for the extension to simply generate footnotes, e.g. by introducing a new ``fncite`` role with a new ``fnbibliography`` directive?

**Comment by drammock** [comment]
I confirm that #185 supports our use case perfectly.  Thanks!  Is this enough to trigger a new minor release, or will we need to wait a while before depending on this?

**Comment by mcmtroffaes** [comment]
Many thanks for testing! I'm currently considering to put this in a separate extension. This has the benefit that a separate footnote extension can support parallel reading (also a long wanted feature). And yes I will trigger a new release for this for sure, once it's fully ready for consumption.

I'm a bit unsure what names to use for the roles, ``fncite`` and ``fnbibliography`` work technically but it looks a bit ugly. ``footnote-cite`` and ``footnote-bibliography`` is clearer but quite long. We could also go for ``cite`` and ``bibliography`` but then the new extension would clash with the old one. It seems unlikely that someone would want to use both footnote citations and regular citation with bibtex, although... it's not impossible that there is a use case, so I think it's best to avoid a name clash. Any suggestions?

**Comment by mcmtroffaes** [comment]
Just to note that I've gone with the conventions from the footbib package (and also named the new extension footbib), i.e. ``footcite`` and ``footbibliography``. This is starting to look pretty good, I'll close this and we can discuss any further details in #185.
