### ISSUE TITLE
suppress "Citation [foo] is not referenced" warning when using `:all:` or `:notcited:`

### ISSUE THREAD

**Issue by drammock** [mcmtroffaes/sphinxcontrib-bibtex#189]
When using `:all:` or `:notcited:` it is presumably the user's intent to render all the bibliography entries *regardless of whether they have been cited anywhere*.  For this reason it seems incorrect to generate "Citation [foo] is not referenced" warnings under such circumstances.

**Comment by drammock** [comment]
I just figured out that this warning is generated by sphinx ([here](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/domains/citation.py#L85-L89)), not by sphinxcontrib-bibtex.  What is the right way forward here? Should I just ignore / swallow the warnings?  Or is this something worth raising as an issue on the sphinx repo?

**Comment by mcmtroffaes** [comment]
I think this is how sphinx intends citations to be used, so, no I don't think it's worth raising this with the sphinx devs. The bibtex extension (in retrospect) misuses the citation nodes to be used also for non-cited keys. So, the solution is to use our own custom nodes to support non-cited entries to appear in the bibliography.

**Comment by drammock** [comment]
for now I've solved this by swallowing the warnings via our `conf.py`. But if I understand you correctly, it sounds like you'll be changing the node type generated by `footbibliography` so the warnings won't get triggered in the first place. Is that right?

**Comment by drammock** [comment]
@mcmtroffaes what is the status of the next release?  Is there anything I can do to help?  FYI, on our doc testing server we have working examples (using your most current `develop` branch) showing:

- multiple `footbibliography` in the same `.rst` document, [here](https://16331-1301584-gh.circle-artifacts.com/0/dev/references.html) ([source here](https://raw.githubusercontent.com/drammock/mne-python/use-bibtex/doc/references.rst); the `footcite`s are hidden using [this trick](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/131#issuecomment-346600383) from #131)

- one giant `bibliography` using `:all:` and `:list: enumerated` [here](https://16331-1301584-gh.circle-artifacts.com/0/dev/bibliography.html) ([source here](https://raw.githubusercontent.com/drammock/mne-python/use-bibtex/doc/bibliography.rst); warnings getting swallowed by conf.py [here](https://github.com/drammock/mne-python/blob/use-bibtex/doc/conf.py#L479-L481))

- various `footbibliography` directives in docstrings ([e.g., here](https://16331-1301584-gh.circle-artifacts.com/0/dev/generated/mne.beamformer.make_dics.html#grossetal2001)) and standalone documentation pages ([e.g., here](https://16331-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/preprocessing/plot_60_maxwell_filtering_sss.html#taulukajola2005))

**Comment by mcmtroffaes** [comment]
Thanks for sharing your experiences. The footbibliography is meant to be used only for the last scenario: standalone local bibliographies as footnotes just for those items that are cited in the current document. Also, if you use ``:list: enumerated`` with ``:all:`` using the old extension, then you should not get any "citation [foo] is not referenced" warnings because no citation nodes are actually created.

The footnote support is there, and I'm fairly happy with it, so there could be a release soon, even though it does not yet fix the original issue that was reported here. The main outstanding issues are documentation and #188.

**Comment by drammock** [comment]
> The footbibliography is meant to be used only for the last scenario: standalone local bibliographies as footnotes just for those items that are cited in the current document. 

OK, but I thought in #190 you added support for the first scenario (multiple `footbibliography` directives in one `.rst` document). It seems to be working that way.

> Also, if you use `:list: enumerated` with `:all:` using the old extension, then you should not get any "citation [foo] is not referenced" warnings because no citation nodes are actually created.

ah, I see you're right. Swallowing the warnings is no longer needed with your latest code. Nice! I think this issue can be closed then?

> The footnote support is there, and I'm fairly happy with it, so there could be a release soon, even though it does not yet fix the original issue that was reported here. The main outstanding issues are documentation and #188.

Looks like #188 is now done. Let me know if you want me to take a stab at the necessary documentation updates (some brief guidance about which changes are not yet documented would help, but if you're too busy I can probably figure it out from looking at the dates in `git blame`). Of course if you prefer to do it yourself that's fine too.

**Comment by mcmtroffaes** [comment]
It looks like this can be closed.
