### ISSUE TITLE
Citation name is not the same with its bibliography reference

### ISSUE THREAD

**Issue by ysig** [mcmtroffaes/sphinxcontrib-bibtex#192]
Hi!

I have the following problem:
I have used your really excellent package for documenting my [library](https://github.com/ysig/GraKeL), but there appears to be a mismatch of how citation entries are entered between the text and in the bibliography references.

For example [here](https://ysig.github.io/GraKeL/latest/kernels/graphlet_sampling.html) the citations reference name `[SGLLopezB17]` is displayed inside the text as `[sugiyama2017graphkernels]`, which the name used as an identifier for citing it (`\cite{sugiyama2017graphkernels}`).
As I have checked this is the case for everything, so I guess this is a general problem (it is the case for all references).

Do you have a clue of what is going wrong?
If you want to check my documentation files you can see them [here](https://github.com/ysig/GraKeL/tree/0.1a7/doc).

Thanks a lot!

**Comment by mcmtroffaes** [comment]
Thanks for reporting. Could you provide a minimal example, with a minimal conf.py and as few extensions as possible, that allows me to replicate the problem? That would be really helpful to get to the cause. I cloned your repository and tried to run sphinx locally but I got lot's of errors, with bib files not found...

**Comment by mcmtroffaes** [comment]
Just running on graphlet_sampling seems to work fine when I run it locally (after fixing the bib file path):

https://github.com/ysig/GraKeL/compare/0.1a7...mcmtroffaes:minimal-example

Please do fix all errors first. If you still see the problem, I'd be happy to reopen the issue.

**Comment by ysig** [comment]
Hi

it finally had to do with the version of sphinx and python2.

Thanks
