### ISSUE TITLE
How to cite a page number?

### ISSUE THREAD

**Issue by jtrakk** [mcmtroffaes/sphinxcontrib-bibtex#193]
Normally when I'm writing LaTeX, to reference a specific page number I use the 
```
\cite[54]{smith2004}
```
style discussed in [this answer](https://tex.stackexchange.com/a/292708/90437).  I've been looking through the docs and issues but haven't seen mention of it.

How do I cite a page number with sphinxcontrib-bibtex?

**Comment by mcmtroffaes** [comment]
I wish I could give you a better answer, but sadly there's no support for special annotations for references in docutils. So you simply have add it in the text directly, for instance:

```rst
:cite:`smith2004` (p. 54)
```
