### ISSUE TITLE
Use in markdown

### ISSUE THREAD

**Issue by dmey** [mcmtroffaes/sphinxcontrib-bibtex#196]
I am writing documentation in markdown ([Commonmark](https://commonmark.org/)) using Sphinx and [recommonmark](https://recommonmark.readthedocs.io/en/latest/index.html) extension. Can I use `sphinxcontrib-bibtex` to render citations and referencing information in markdown files?

**Comment by mcmtroffaes** [comment]
That would be cool, but I honestly have no idea... If you manage to make that work, please let me know. I'd be happy to add it to the test suite and to the documentation.

**Comment by chrisjsewell** [comment]
FYI now you can do this in [myst-parser](https://myst-parser.readthedocs.io/en/latest/) 😀

**Comment by mcmtroffaes** [comment]
Ow, that's very nice! I guess this can be closed then. Thank you so much @chrisjsewell for sharing this here.
