### ISSUE TITLE
Fix bibliography w/ references on different page problem using a post-transform?

### ISSUE THREAD

**Issue by choldgraf** [mcmtroffaes/sphinxcontrib-bibtex#197]
Hey there - we have been making good use of this extension over in [jupyter book](https://jupyterbook.org), it is great!

We were thinking about how to get around the issue of citations not resolving when they're on a different page from the bibliography ([ref](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#unresolved-citations-across-documents)).

From looking at the [bibliography transform](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/develop/sphinxcontrib/bibtex/__init__.py#L124), I wonder if this issue could be resolved by using a **post-transform** instead of a transform. Post-transforms are run *after* the initial `doctree` parse, so they'll only be run *after* all of the pages have been read.

Do you think that this would resolve the problem of missing references because the bibliography page came before the page with a reference?

(for an example of all the sphinx events we opened up an issue to discuss this here: 
https://github.com/sphinx-doc/sphinx/issues/7215)

**Comment by mcmtroffaes** [comment]
I'm fairly (but not 100%) sure citation and footnote nodes are processed in the regular transform phase, so I don't think it would work in the current design just to move the transformation to another phase. Post-transform is too late, and we'd need to duplicate the non-trivial work sphinx does to resolve all references. I have another idea for solving the problem at the moment, similar to how LaTeX solves it by storing citation information in an auxiliary file. But I haven't implemented it yet.

Anyway, good job on opening an issue on clarifying what sphinx actually does! Very helpful. I have a simplified model of it in my head but I've never really seen it written down, kudos to you!

**Comment by mcmtroffaes** [comment]
I'm very glad to say this has now been implemented (not using a post-transform, but instead using multiple passes, and a separate json file that stores citations)!

**Comment by choldgraf** [comment]
this is super cool @mcmtroffaes , great improvement!

**Comment by mcmtroffaes** [comment]
I wasn't expecting such a quick reply! :D Thanks!! Be sure to test it out on develop if you have a chance. If there are any usage issues, do let me know. The documentation of the feature is here at the top of the usage.rst file:

https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/develop/doc/usage.rst

I'll be adding support for parallel builds, then merge the new footnote feature into the main bibtex extension, and that should make for a nice new Christmas release.
