### ISSUE TITLE
Change inline citation format?

### ISSUE THREAD

**Issue by matthew-brett** [mcmtroffaes/sphinxcontrib-bibtex#201]
I'm very sorry if I missed this - I probably did - but is there a way to configure the inline citation format?  So we get - say:

```
as Einstein (1901) said
```

intead of 

```
as [Ein01] said
```

?

**Comment by mcmtroffaes** [comment]
That's a good question, but the answer is no, not at the moment. The extension simply translates the :cite: roles to standard sphinx citation nodes, so it will stick with that formatting.

**Comment by matthew-brett** [comment]
Is there a reason that the node has to have that text though?  I think the relevant code is here:  https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/develop/sphinxcontrib/bibtex/__init__.py#L78

Given you're returning a Text node, I guess that text can by anything?  Is there a way to look up the bibliography entry in that text, and so get e.g. author names, years, etc?

**Comment by mcmtroffaes** [comment]
Ah, right. You can use a custom pybtex labelling style to make that text to be whatever you want. So, you'd code that on the pybtex end, similar to how you tune other aspects on the rendering. There's an example in the test suite here which reverts to using the key, but it's easy to adapt to use year/author labels:

https://github.com/mcmtroffaes/sphinxcontrib-bibtex/tree/develop/test/custom_labels

Does that help you further?

**Comment by mcmtroffaes** [comment]
... and also see the discussion here: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/pull/174

**Comment by mcmtroffaes** [comment]
I suspect this can be closed? If there's still anything concerning custom labelling that is unclear (either from the documentation, or some missing feature), do let me know.

**Comment by matthew-brett** [comment]
I guess leave open if you want folks to find this for the discussion, or you think that you might do more support for configuration of inline citations later.  Otherwise feel free to close.

**Comment by mcmtroffaes** [comment]
The develop branch now supports natbib style inline citations with ``:cite:t:`` and ``:cite:p:`` with tons of variants, and with every aspect of inline citations fully customizable (whether to have brackets, what the brackets are, how to format separators, what part of the inline citation gets the link, ...). I'll write some documentation for this and then it will be included with the next release, hopefully not too long from now.

**Comment by matthew-brett** [comment]
Great!  Thank you!
