### ISSUE TITLE
Allow for citation labels not to be surrounded by brackets

### ISSUE THREAD

**Issue by amichuda** [mcmtroffaes/sphinxcontrib-bibtex#203]
Would it be possible to have citations that around square brackets? I might not be pointing at the right part of the code right now, but square brackets are hardcoded:

https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/5a9e444d3c31fb0807b8cfbf593b77159f19f696/sphinxcontrib/bibtex/__init__.py#L78

I know that we can create custom labels with `pybtex`, but that's just for what goes inside the brackets, correct? is there some way to get rid of the brackets or have them be replaced by parantheses if we wish?

**Comment by mcmtroffaes** [comment]
Docutils hardcodes the square brackets by convention for the citation role. I'm not sure if there's an easy way to change that in a way that does not break other things. Did you try if it works if you change the brackets in the ``bibtex/__init__.py`` code?

**Comment by mcmtroffaes** [comment]
The develop branch now supports natbib style inline citations with ``:cite:t:`` and ``:cite:p:`` with tons of variants, and with every aspect of inline citations fully customizable (whether to have brackets, what the brackets are, how to format separators, what part of the inline citation gets the link, ...). I'll write some documentation for this and then it will be included with the next release, hopefully not too long from now.

**Comment by amichuda** [comment]
This looks awesome! Thank you so much

**Comment by choldgraf** [comment]
@mcmtroffaes this is really great! thank you 🙏🙏🙏

Please do ping when there's docs and I'm happy to give it a shot and provide feedback

**Comment by mcmtroffaes** [comment]
@choldgraf Thanks, it's much appreciated! There are some docs indeed. I've created new issue here for wider discussion: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/232
