### ISSUE TITLE
unresolved citations in autodoc parameter description

### ISSUE THREAD

**Issue by dizcza** [mcmtroffaes/sphinxcontrib-bibtex#204]
Does not work ([source line](https://github.com/INM-6/elephant/blob/50106b73a112eeef8dde84b0bf01a802efed4259/elephant/spike_train_correlation.py#L615)):
```rst
Parameters
----------
cross_correlation_coefficient : bool, optional
    If True, a normalization is applied to the CCH to obtain the
    cross-correlation  coefficient function ranging from -1 to 1 according
    to Equation (5.10) in :cite:`correlation-Eggermont2010_77`. See Notes.
    Default: False
```
Works:
```rst

Cross-correlation coefficient is computed according to
:cite:`correlation-Eggermont2010_77`.

Parameters
----------
cross_correlation_coefficient : bool, optional
    If True, a normalization is applied to the CCH to obtain the
    cross-correlation  coefficient function ranging from -1 to 1 according
    to Equation (5.10) in :cite:`correlation-Eggermont2010_77`. See Notes.
    Default: False
```
In the first case, the citation is not rendered and not displayed in the built HTML page, the behavior is similar to #200, though my bib usage is:

```rst
References
----------

.. bibliography:: ../bib/elephant.bib
   :labelprefix: cor
   :keyprefix: correlation-
   :style: unsrt
```

Built HTML page: https://elephant-docs-development.readthedocs.io/en/docs-more/reference/spike_train_correlation.html. Note: `cor3` citation is missing.

I looked at [Unresolved Citations Across Documents](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#unresolved-citations-across-documents), but `:all:` directive is not a solution - I want to list specific citations only.

Is it a bug or I'm missing something?

-------

Update.
The readthedocs link now shows all citations because I did put the citation on top as a temporary fix.

**Comment by mcmtroffaes** [comment]
Did you verify that the bibliography directive is processed last? To ensure proper operation, I recommend having a single bibliography directive in a file that is processed last as suggested in the documentation. That doesn't seem to be the case from what I can see from your code. Alternatively, you could put the bibliography directive directly into the docstring that does the citing.

**Comment by dizcza** [comment]
> Did you verify that the bibliography directive is processed last?

I do put the bibliography directive at the bottom of each .rst file, or what do you mean?

For example, here is the full content of the RST file I'm talking about - one of the RST module files that are indexed sequentially:

```rst
=======================
Spike train correlation
=======================


.. automodule:: elephant.spike_train_correlation


References
----------

.. bibliography:: ../bib/elephant.bib
   :labelprefix: cor
   :keyprefix: correlation-
   :style: unsrt
``` 

`elephant/spike_train_correlation.py` source file does not contain any other reference sections.

**Comment by mcmtroffaes** [comment]
Yes, I would expect that to work. It looks like the parameter descriptions get processed too late by docutils.

**Comment by mcmtroffaes** [comment]
To try to reproduce the problem, I've added a test for this in the test suite:

https://github.com/mcmtroffaes/sphinxcontrib-bibtex/tree/develop/test/autodoc

In the test it works. I'm not sure what's going wrong for you. Can you provide a minimal test case that reproduces the problem, ideally just using the autodoc and bibtex extensions, with a single rst file and a single module file?

**Comment by dizcza** [comment]
> Can you provide a minimal test case that reproduces the problem, ideally just using the autodoc and bibtex extensions, with a single rst file and a single module file?

https://github.com/dizcza/sphinx-bibtex-bug

```                               
/home/ulianych/PycharmProjects/sphinx-bibtex-bug/elephant/signal_processing.py:docstring of elephant.signal_processing.wavelet_transform:21: WARNING: citation not found: signal-Farge1992_395
/home/ulianych/PycharmProjects/sphinx-bibtex-bug/elephant/spike_train_correlation.py:docstring of elephant.spike_train_correlation.cross_correlation_histogram:69: WARNING: citation not found: correlation-Eggermont2010_77
/home/ulianych/PycharmProjects/sphinx-bibtex-bug/elephant/spike_train_correlation.py:docstring of elephant.spike_train_correlation.cross_correlation_histogram:114: WARNING: citation not found: correlation-Eggermont2010_77
```

**Comment by mcmtroffaes** [comment]
Thanks for putting this together, however this is still quite far from a minimal self-contained test. If you could slim it down as suggested (single rst, single module included with the test, no extensions besides autodoc & bibtex), that would speed things up.

**Comment by dizcza** [comment]
Done.

**Comment by mcmtroffaes** [comment]
Thanks! Looks like this is due to the autosummary extension creating new documents which are processed only after the bibliography directive. The way to fix this is to have one single bibliography rst file for the entire project that comes last, for instance as follows:

https://github.com/mcmtroffaes/sphinx-bibtex-bug/tree/feature/fix-autosummary-issue

**Comment by dizcza** [comment]
As I said in the very beginning,

> I looked at Unresolved Citations Across Documents, but :all: directive is not a solution - I want to list specific citations only.

I do not want to have one .rst file with all bibtex references there. This is inconvenient. I'm using `:keyprefix:` and `:labelprefix:` features that are made specifically to address inconveniences of cluttered references. I want to cite each module independently such that each module lists references.

**Comment by mcmtroffaes** [comment]
If you have many of these, you could try to move the bibliography directive in the appropriate part of the long description part of the docstrings so it ends up in the autosummary generated files. If you can make it so that these appear at the bottom and consistently come alphabetically last, it might work.

Alternatively, you could use the footcite role from the bibtex2 extension (in develop) to have references that are local to each document. This is still experimental and the interface/features might still be subject to change if issues are found, but it might do the trick for you. You'd need a footbibliography directive at the bottom of any document that has citations (so also in the autosummary generated files).

**Comment by mcmtroffaes** [comment]
Actually, I just found another trick: put the generated documents in "adoctree" instead of "doctree". That will cause them to be processed first. See https://github.com/mcmtroffaes/sphinx-bibtex-bug/tree/feature/fix-autosummary-issue2

**Comment by dizcza** [comment]
Using `_toctree` instead of `toctree` works though it's definitely confusing for other developers who don't understand/know about this bug. I'll use it as a temporary fix.
The other ideas are not transparent and maybe I'll come back to rethink the hotfix once you provide examples to users.

**Comment by mcmtroffaes** [comment]
Agreed this is confusing. I've added the autosummary workaround to the documentation now.
