### ISSUE TITLE
ignore newlines/whitespace around cite keys

### ISSUE THREAD

**Issue by dizcza** [mcmtroffaes/sphinxcontrib-bibtex#205]
Does not work:
```python
def spade():
    """
    Perform the SPADE :cite:`spade-Torre2013_132,spade-Quaglio2017_41,
    spade-Stella2019_104022` analysis ...
    """
```
Works:
```python
def spade():
    """
    Perform the SPADE :cite:`spade-Torre2013_132`,
    :cite:`spade-Quaglio2017_41`, :cite:`spade-Stella2019_104022` analysis ...
    """
```

With the hope of someone solving #94 in mind, the former usage is recommended but it does not work. Sphinx build says "WARNING: citation not found:  spade-Stella2019_104022" and it's not rendered in the final HTML page.

**Comment by mcmtroffaes** [comment]
Multiple citations in a single cite are currently not supported. When they are, one could have a look at this. I'm unsure if interpreted text is meant to go across multiple lines in sphinx, though. Closing for now, in favour of #94.

**Comment by dizcza** [comment]
You misunderstood me, and closing the issue was premature.

Multiple citations are supported, and you've added this feature in https://github.com/mcmtroffaes/sphinxcontrib-bibtex/pull/65

works 3:

```python
def spade():
    """
    Perform the SPADE :cite:`spade-Torre2013_132,spade-Quaglio2017_41,spade-Stella2019_104022` analysis.
    """
```

**Comment by mcmtroffaes** [comment]
I'm still not sure what it is exactly that you are requesting. Are you asking for whitespace (including newlines) around commas to be ignored in the interpreted text of :cite: roles?

**Comment by dizcza** [comment]
> Are you asking for whitespace (including newlines) around commas to be ignored in the interpreted text of :cite: roles?

Exactly. Or is it a Sphinx limitation that does not allow breaks in a line with ticks?
