### ISSUE TITLE
Feature request: Add possibility to tag citations to allow using a single project-wide bib file?

### ISSUE THREAD

**Issue by HTenkanen** [mcmtroffaes/sphinxcontrib-bibtex#216]
Hi @mcmtroffaes and thanks for the great work you're doing with the extension! 👍🏻 

We are using sphinxcontrib-bibtex with JupyterBook for writing our [book](https://python-gis-book.readthedocs.io/en/develop/).

As you may guess, we have quite a complicated setting in terms of citations, as we have separate Reference lists at the end of each chapter. Currently, we basically have separate .bib files for each chapter, which works but is a bit of a hassle. 

For us, the optimal solution would be to have a possibility to maintain a single bib file with all references for our book. The new `footcite` almost does the thing, but the issue for us, is the fact that our citations e.g. for "chapter 1" are distributed into multiple separate documents (having all text for Chapter 1 in a single doc unfortunately isn't possible). 

So, thinking of this scenario, I was wondering whether it would be possible to **tag** the citations + have the possibility to add the bibliography based on a given tag?

E.g. something like:
`footcite{Tenkanen2020,Author2021::chapter-1}` 
`.. footbibliography::chapter-1`

So with the citation you could give a tag after `::` and then all citations (and only those) having tag `chapter-1` would be listed in the reference list when the bibliography is added. 

I think by looking at the current approach that parses the separate `bibtex.json` file, doing something like this and organizing the references by tags should be possible (haven't checked the source codes though). 

Ping @chrisjsewell

**Comment by mcmtroffaes** [comment]
Thanks for posting your issue. I understand the problem, but I'm not sure that I understand your proposed solution. Footnotes in sphinx are inherently set up to resolve per document, and do not work across documents.

Would the label/key prefix features of the standard bibliography directives resolve your issue?

https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#label-prefixing
https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#key-prefixing

**Comment by mcmtroffaes** [comment]
@HTenkanen Did you manage to resolve your issue using the features I mentioned previously?

**Comment by mcmtroffaes** [comment]
Closing due to non-response. Feel free to reopen if there's still something needing to be addressed.
