### ISSUE TITLE
KeyError: BibliographyKey(docname='index', id_='id1')

### ISSUE THREAD

**Issue by jedbrown** [mcmtroffaes/sphinxcontrib-bibtex#221]
I've encountered this on RTD when building latexpdf with the new version 2.1.0, but have not been able to reproduce locally so it might not be a sphinxcontrib-bibtex bug. However, the exception comes from code that was just changed (#219) so I'll start here.

```
  File "/home/docs/checkouts/readthedocs.org/user_builds/libceed/envs/jed-doc-fixes/lib/python3.8/site-packages/sphinxcontrib/bibtex/transforms.py", line 75, in run
    bibliography = domain.bibliographies[bib_key]
KeyError: BibliographyKey(docname='index', id_='id1')
```

The HTML builds are clean on RTD and both HTML and latexpdf succeed locally.

**Comment by mcmtroffaes** [comment]
Thanks for reporting. I've managed to reproduce it locally from your repository, looking into it.

**Comment by mcmtroffaes** [comment]
I've just released a hotfix for this. Can you check in your project if the latest version now works on RTD? There was also an issue with the citation references, so if you could verify that the generated pdf has the correct citations as well as correct citation references, that would be swell.

**Comment by jedbrown** [comment]
Thanks! I spot-checked a few citation references and they all look good.

**Comment by mcmtroffaes** [comment]
Awesome! Thanks for checking.
