### ISSUE TITLE
get_all_cited_keys can fail if some docnames are not findable from the root

### ISSUE THREAD

**Issue by wence-** [mcmtroffaes/sphinxcontrib-bibtex#229]
Consider a situation where a sphinx site has some `rst` files which contain citations, but these files are not explicitly linked from the root of the documentation tree. This happens for us because we have effectively "static" pages that are linked from a pre-generated header (rather than part of the autobuilt documentation).

In this situation, the visit of all files will correctly determine that these rst files need citations. However, the implementation of `get_docnames` in domain.py will not find these files, and we get an error.

As far as I can tell, `get_docnames` only needs to determine all the docnames in the current environment (rather than having them in order or similar). So I can fix this by replacing it with:

```python
def get_docnames(env):
    """Get all document names in the environment."""
    yield from env.project.docnames
```

Is there any reason not to do this?

**Comment by mcmtroffaes** [comment]
As for your question: the docnames must be in order, otherwise citations won't be in order when using unsorted pybtex styles. As for the issue: this was reported already here #228, so closing as a duplicate.

**Comment by wence-** [comment]
Apologies for not checking the issue list more thoroughly. Thanks for the quick fix and response!

**Comment by mcmtroffaes** [comment]
That's ok, thanks for taking the effort to report it. I rather have a duplicate than an unnoticed problem!
