### ISSUE TITLE
new customizable citation reference styles [develop branch, feedback requested]

### ISSUE THREAD

**Issue by mcmtroffaes** [mcmtroffaes/sphinxcontrib-bibtex#232]
The docs are there mostly, so I guess this is ready for some real world testing and feedback. The relevant parts of the docs are currently here:

* https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#roles-and-directives - for the new roles
* https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#custom-inline-citation-references - for how to customize existing styles

However, I'm planning to swap out the pybtex template system for a new one that is easier to extend for formatting custom data. That work is happening over here: https://github.com/mcmtroffaes/rite The basic functionality and the way of changing separators and brackets is probably not going to change (i.e. as in the example in the docs), however the syntax for creating completely new citation reference styles from templates will likely change.

I plan to document how to create new styles from scratch using templates when rite is ready. But any feedback now would already be useful.

**Comment by edmundsj** [comment]
Can these be added to the :footcite: directive as well as the :cite: directive? :footcite:t: would be very nice. I am primarily using the former, as I use Sphinx for all my documentation, and have a massive sprawl of documents, all of which need references, so a single global set of references (and only one bibliography) is not my use case at all. I am also getting an error when trying to use :cite:t. I suspect this is because the pip version is still on 2.1.4 and this was introduced in 2.2.0 :)p
```
WARNING: Unknown interpreted text role "cite:t".
```

**Comment by mcmtroffaes** [comment]
This issue is for feedback for the next release, currently on the develop branch. You have to install from git to try it out. But yes, there's no similar role for footnotes yet. That's definitely one of the things to add.

**Comment by choldgraf** [comment]
Hmmm - some quick feedback as upgrading to this popped up some errors in my docs build and I'm not sure why.

I tried updating to the alpha release of sphinxcontrib-bibtex (which by the way I could not find on PyPI? is it not there?). Building the docs yielded errors that seemed to suggest that the citations were clashing with Sphinx's "any" role. I had been using labels to refer to titles, and referencing them elsewhere, and those labels were not getting picked up by Sphinx. The build then crashed with an error like

```
envs/dev/lib/python3.7/site-packages/docutils/nodes.py", line 627, in __getitem__
    return self.children[key]
IndexError: list index out of range
```

Any thoughts there? And do you have instructions for installing the alpha release from PyPI? It would make it a bit easier to debug this in our CI builds.

**Comment by mcmtroffaes** [comment]
Well, you cannot install the git version directly from PyPI, but you can install it directly with pip:

```
pip install git+https://github.com/mcmtroffaes/sphinxcontrib-bibtex.git
```

Does this help?

**Comment by choldgraf** [comment]
Yeah I know about that - I was going to see what happened if I upgraded this in the sphinx book theme, but that lists the dependency via `setup.py`, not `requirements.txt`, and I can never remember how to make `setup.py` point to a github repository. I will try and figure it out

**Comment by choldgraf** [comment]
Figured it out, though now I've just confirmed that upgrading does in fact break our docs builds for some reason haha

https://readthedocs.org/projects/sphinx-book-theme/builds/13012285/

**Comment by mcmtroffaes** [comment]
Great, thanks for trying it out and letting me know. I'll see if I can reproduce this.

**Comment by mcmtroffaes** [comment]
I have this reproduced now. It looks like it's a bug in the myst-parser:

https://github.com/executablebooks/MyST-Parser/blob/07ac8596f2171be993c931b4e58de93ed940c9c0/myst_parser/myst_refs.py#L147

You need to check that res actually has children (i.e. len(res) > 0). For example,

```python
>>> from docutils.nodes import inline
>>> x = inline()
>>> len(x)
0
>>> bool(x)
True
```

This said, it's probably a good idea to try to implement the resolve_any_xref function anyway.

**Comment by mcmtroffaes** [comment]
The issue is now fixed. I'd still encourage you to fix the problem in myst-parser, as there's no guarantee that extensions will return a reference node with length larger than zero.

**Comment by chrisjsewell** [comment]
> I'd still encourage you to fix the problem in myst-parser, as there's no guarantee that extensions will return a reference node with length larger than zero.

thanks for the fix @mcmtroffaes 😄.
Just to note, although it does appear to be a bug, this particular code is directly copied from sphinx, so it would have failed exactly the same without myst-parser: https://github.com/sphinx-doc/sphinx/blob/c60cc0c1788a1667913fa36f4c77ea90c4ff809e/sphinx/transforms/post_transforms/__init__.py#L128

**Comment by mcmtroffaes** [comment]
You're welcome. And, aye, looks like upstream has the same issue too.

**Comment by chrisjsewell** [comment]
yeh maybe sphinx/myst-parser should also log a warning about a domain not implementing a `resolve_any_xref` method, since would have never noticed you were not (and should be) implementing it if it were not for this bug

**Comment by choldgraf** [comment]
Yeah - so this feels like a missing warning in Sphinx (for the any xref method). Did anybody open an issue about it? If not I'm happy to do so. Is the error that we got here also where the check and warning should happen?

**Comment by chrisjsewell** [comment]
In myst-parser a warning is now raised (that can be suppressed): https://github.com/executablebooks/MyST-Parser/pull/313

**Comment by choldgraf** [comment]
Just a quick idea @mcmtroffaes on the custom brackets issue. I was thinking through how it could be simpler for people to define custom formatting for inline citations, bibliographies, etc. Have you thought about defining this simply with a template-style pattern, rather than a python object with classes and properties?

E.g., you could use a configuration like

```
bibtex_inline_style = "[{{author-list}}]"
bibtex_author_list_style = "{{ authors | join ', ' }}"
``` 
and then if people wished to modify the inline style, in their own `conf.py` they'd modify that value to instead be something like

```
bibtex_inline_style = "({{author-list}})"
```

I think then you'd need to define a few variables that they'd have access to, and that would be "inserted" into the style that they specify whenever a reference is made. I wonder if this would make it lower-barrier rather than defining their own python classes and such.

I can't tell if I'm making any sense here, but curious what you think!)

**Comment by mcmtroffaes** [comment]
Thanks, that's an interesting suggestion. I can see how using standard python string templates makes sense from a user perspective, since it's a lot more common to define templates that way.

However, from a design perspective, the inline styles must distinguish between *a lot* of different commands: textual, parenthetical, label, year, author, possibly other commands that users can add (e.g. it is very simple for users to add a new :cite:title: inline citation command), and then several variations for each of these (start with capital letter or not, full authors or not), each with their own brackets, separators, naming conventions, and possibly referring to custom bibtex entry fields. Having them as python dataclasses allows high level composition and reuse, and allows the user to hook directly into the pybtex formatting system. I'm not convinced that string based templates are suitable for this purpose. Yes, it's a bit more complicated for users, but with that, it brings a very powerful customization system. It's important though that there's good documentation.

**Comment by mcmtroffaes** [comment]
On a side note, I've posted a patch for Sphinx for the any reference issue.

**Comment by choldgraf** [comment]
@mcmtroffaes makes sense...will think on it more. I think it's going to require a very dedicated user to write their own python classes and register them and such, but can see how this is a combinatorial challenge.

**Comment by mcmtroffaes** [comment]
Yes, it's the same with pybtex's bibliography styles, needing to write python code. Thanks to the entry point system, it is super easy for external modules to provide additional styles that can be used with sphinxcontrib-bibtex. But having a few of the most common styles available to users directly within sphinxcontrib-bibtex would be a good idea.

**Comment by choldgraf** [comment]
@mcmtroffaes to be honest I bet that also offering one option with parentheses rather than brackets would get close to that 90%, since you also now have the "cite without any enclosing symbols" options as well via the role

**Comment by mcmtroffaes** [comment]
Thanks all for the feedback, everyone! This is now part of the release, so closing.
