### ISSUE TITLE
Use github workflows to build, test, and deploy to pip on push

### ISSUE THREAD

**Issue by edmundsj** [mcmtroffaes/sphinxcontrib-bibtex#233]
So I can't tell, but it *looks like* this repository doesn't currently auto-build and test on a push to github and auto-push to the pip repository, and this is causing the version on pip to be out-of-date with some of the updates. You can use github workflows to do this, it's reasonably well-documented and I have done it before (see https://github.com/edmundsj/RCWA/tree/master/.github/workflows for my github workflows file, which builds, tests, and deploys to pyPI if all the tests pass). Github workflows is actually quite good.

**Comment by mcmtroffaes** [comment]
I can't help you with the pip repository, but the latest version on pypi looks fine.
