### ISSUE TITLE
cut a release? 🙃

### ISSUE THREAD

**Issue by choldgraf** [mcmtroffaes/sphinxcontrib-bibtex#236]
Just wondering if there's a plan on when the `a0` will be dropped from the current version! Once it's dropped I wanna document it in Jupyter Book :-)

**Comment by mcmtroffaes** [comment]
I leaving some time to see if there's any further comments on #232 and/or bugs anyone finds with the new citation system, so probably within a few weeks.

**Comment by choldgraf** [comment]
OK lemme try playing around with https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/232 and if I have any thoughts I'll share them!

**Comment by mcmtroffaes** [comment]
Sure, thanks, that would be great!

**Comment by choldgraf** [comment]
@mcmtroffaes do you think you could cut a patch release just with the fix for the:

```
'sphinxcontrib.bibtex.domain::cite' has not implemented a `resolve_any_xref` method
```

error in it? This is causing a ton of our builds to fail...
