### ISSUE TITLE
Return version

### ISSUE THREAD

**Issue by lcnittl** [mcmtroffaes/sphinxcontrib-bibtex#239]
Would you mind adding (or accepting a PR) returning of current extension version?

This would allow the use of:

```py
needs_extensions = {"sphinxcontrib.bibtex": "2.2.0"}
```

to require a specific version (which makes sense I think for the changed from v1 to v2). Currently using `needs_extensions` yields

```
(.venv) PS C:\path\to\docs> .\make.bat html
Running Sphinx v3.5.3
loading translations [en]... done

Sphinx version error:
This project needs the extension sphinxcontrib.bibtex at least in version 2.2.0 and therefore cannot be built with the loaded version (unknown version).
```

Overall, this would require only adding `return {"version": version}` (with `version` being a `x.y.z` string) like e.g. [here](https://github.com/sphinx-contrib/email/blob/master/src/sphinxcontrib/email/__init__.py) (no need to go fancy and use scm version like I did).

Thanks for your consideration!

**Comment by mcmtroffaes** [comment]
Sure, that's a good suggestion.
