### ISSUE TITLE
`bibtex_style` and `bibtex_reference_style` doesn't render with footcite

### ISSUE THREAD

**Issue by NicolasGensollen** [mcmtroffaes/sphinxcontrib-bibtex#240]
Hi,

I'm using sphinxcontrib-bibtex 2.2.0 in a project in which I want to use author-year reference style with footcite. I'm probably doing something wrong, but it seems like the rendering is not taking the values of the variables `bibtex_style` and `bibtex_reference_style` into account. 

Basically, my settings in `conf.py` look like this:
```python
extensions = [...
    'sphinxcontrib.bibtex',
    ...]
...
bibtex_bibfiles = ['./references.bib']
bibtex_style = 'unsrt'
bibtex_reference_style = 'author_year'
bibtex_footbibliography_header = ''
...
```

and I have some python file in which I'm trying to use footcite:
```python
def foo():
    """Check out this great paper: :footcite:`bib-key`.

    References
    ---------
    .. footbibliography::
```

But the rendering looks like this:

![bibtex1](https://user-images.githubusercontent.com/2639645/114868206-f4877b00-9df5-11eb-86f4-a978b6c06827.png)

and: 

![bibtex2](https://user-images.githubusercontent.com/2639645/114868224-f94c2f00-9df5-11eb-9bae-66224516ae00.png)

I tried changing the values in `conf.py` but it doesn't seem to change the rendering. However, if I set them to invalid values, I get an error.

Any idea what I'm doing wrong here?
Thanks!

**Comment by mcmtroffaes** [comment]
Changing ``bibtex_style`` should work (although labels are not rendered for footnotes, so you will not notice a difference if you only use the built-in styles). ``bibtex_reference_style`` currently only works with ``:cite:t:`` and ``:cite:p:``. However, textual/parenthetical citations for footnote references will at some point also be supported; you can subscribe to #234 to keep informed of any updates. Does this help?

**Comment by NicolasGensollen** [comment]
Thanks for the quick answer @mcmtroffaes !
Yes, it does help! I'll keep an eye on #234 then, and close this one.

**Comment by mcmtroffaes** [comment]
Awesome, thanks again for your interest!

**Comment by mcmtroffaes** [comment]
@NicolasGensollen The ``:footcite:t:`` and ``:footcite:p:`` roles are now available in the develop branch. If you like, feel free to give it a spin, and be sure to let me know if you have any troubles with the new feature. I hope to cut another release soon if no bugs around it turn up.

**Comment by NicolasGensollen** [comment]
Thanks a lot @mcmtroffaes ! :+1: 
I will definitely have a look at this!
