### ISSUE TITLE
Prepared for sphinx 4?

### ISSUE THREAD

**Issue by chrisjsewell** [mcmtroffaes/sphinxcontrib-bibtex#241]
Heya 👋  sphinx version 4 is being released imminently, so you might want to do some testing on the beta release?
One reason I mention this specifically, is that there is no upper pinning in your requirements.txt for sphinx (just `sphinx>=2.1`)

**Comment by mcmtroffaes** [comment]
Oh, thanks for the heads up. It's probably a good idea to add testing for the latest sphinx head anyway. Have you tried it yourself yet?

**Comment by mcmtroffaes** [comment]
Tests are passing locally for me on sphinx-4.0.0b1. Be sure to let know if you have any issues!

**Comment by mcmtroffaes** [comment]
Looks like travis has some troubles respecting the docutils<0.17 requirement from Sphinx 3.5.4. No idea why this is happening (pip bug??), but this should resolve itself when Sphinx 4.0.0 is out.

**Comment by chrisjsewell** [comment]
Cheers, yeh I don't believe sphinx 3 pins docutils. 

Well I'm slowly getting round to it, but do have to deal with some depreciations
