### ISSUE TITLE
"duplicate citation for key" warning; even though it's just fine?

### ISSUE THREAD

**Issue by robertgiessmann** [mcmtroffaes/sphinxcontrib-bibtex#243]
Hi @mcmtroffaes et al., 

I am compiling a documentation (actually via jupyter-book, https://github.com/executablebooks/jupyter-book ). 

One markdown file has two references to the same citation key, which also works completely fine -- in the local bibliography I get two back-references to the two occurences.

However, I think that sphinxcontrib-bibtex is throwing a warning on this. The line is:

```
#12 8.476 /app/content/recipes/interoperability/identifier-mapping.md:313: WARNING: duplicate citation for key "batchelor_scientific_nodate"
```

and I found the error code here as well: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/77df760973d08b1eede7f9b7696fc650d934c5bd/sphinxcontrib/bibtex/domain.py

I couldn't quite think through the if logic there; could you maybe check whether my try to explain the behavior is plausible and whether there is a logic error in your code? If not, I might share the whole document and/or conduct further testing?

Let me know! Thanks in advance,
   Robert

**Comment by mcmtroffaes** [comment]
The error means that you have two or more bibliographies that contain the same citation, so the extension warns you. Having two or more references to the same key is fine. Happy to have a look at the source to see where the culprit is, or whether it is a genuine bug.

**Comment by robertgiessmann** [comment]
Thanks for the very quick repsonse! The code lives here: https://github.com/FAIRplus/the-fair-cookbook 

But I can investigate next week, too, by drilling down into a minimal example I can handle better than the gigantic mess we produce there... I will come back to you then, if you like? :) Have a nice weekend!

**Comment by mcmtroffaes** [comment]
You're welcome. And yes, having a minimal example would certainly help!

**Comment by robertgiessmann** [comment]
Hi @mcmtroffaes , I investigated, aaaaand I read your documentation. Guess what. ;) 

You already said in the documentation that one gets problems when doing multiple bibliographies -- I thought I would be clever with doing a `filter: docname in docnames`, but it's not sufficient. What works, though, is your proposed `footcite` / `footbibliography` solution.

Thanks for your responses! I will close this issue now, as it is solved for me.

**Comment by mcmtroffaes** [comment]
Oh, that must have been a tricky one to track down! Yes, footbibliography is probably what you need if you do not have a central bibliography document. Glad you sorted it out.
