### ISSUE TITLE
inconsistent latex and html output with :cite:, double square brackets, version 2.2.0

### ISSUE THREAD

**Issue by zhi-wang** [mcmtroffaes/sphinxcontrib-bibtex#244]
In PDF, they read `[[1]]`, `[[2]]`, etc., whereas in html, they read `[1]`, `[2]`, etc.

The outer brackets are hardwired in the tex file as `{[}\sphinxcite{refs:id5}{]}`, which I believe is the cause of the double square brackets.

If I use `:cite:label`, the PDF output looks fine to me but html loses the square brackets.

The bib style is `unsrt`.

Any comments and workarounds?

Thanks.

**Comment by mcmtroffaes** [comment]
Thanks for reporting. Do you have a small example to reproduce the problem?

**Comment by mcmtroffaes** [comment]
Never mind, I managed to reproduce it.

**Comment by mcmtroffaes** [comment]
Superseded by #246.

**Comment by mcmtroffaes** [comment]
Sorry, accidentally closed the wrong issue. 😄

**Comment by mcmtroffaes** [comment]
Fix now merged in develop, closing. Thanks again for your report and help with testing!
