### ISSUE TITLE
Add a footnote citation at the end of a sentence

### ISSUE THREAD

**Issue by hagenw** [mcmtroffaes/sphinxcontrib-bibtex#256]
It is not uncommon to write a footnote in English like this:

> ... curve.¹

As I cannot write the role directly after the `.` in RST I can only write:

```rst
... curve. :footcite:`Name2021`
```

which produces

![note_wrong](https://user-images.githubusercontent.com/173624/125063753-2a17c980-e0b0-11eb-9d8c-e40c390772b8.png)

It should more look like this

![note_correct](https://user-images.githubusercontent.com/173624/125063772-30a64100-e0b0-11eb-931b-942e7f8a9a86.png)

Is there a trick to make this work?

**Comment by mcmtroffaes** [comment]
I've been wondering about this too. The problem is that sphinx roles need to be surrounded by spaces. Can you try if this works (lifted from https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html concerning inline markup)?

```rst
... curve.\ :footcite:`Name2021`
```

**Comment by hagenw** [comment]
Cool, this works indeed:

![image](https://user-images.githubusercontent.com/173624/125064835-5bdd6000-e0b1-11eb-8b42-e336a124c000.png)

Thanks for pointing me to https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html, I tried to find something like this, but did not succeed. Maybe it's worth adding a hint to the docs of `sphinxcontrib.katex`.

**Comment by mcmtroffaes** [comment]
Yeah absolutely, this should go straight with the ``:footnote:xxx:`` docs! Thanks for trying it out and confirming this fix.
