### ISSUE TITLE
render "\url" statements as hyperlinks

### ISSUE THREAD

**Issue by IAXES** [mcmtroffaes/sphinxcontrib-bibtex#258]
Good day,

I have a large number of references to online resources in a document I'm compiling. The entries themselves are of the following form:

```
@Misc{giassa-1,                                                                  
    title = {{Cloud Native DevOps: Migrating from Monolithic Development}}, 
    note = {\url{https://github.com/IAXES/pronk8s}, accessed 2021-07-05},   
    author = {Matthew Giassa}                                               
}                                                                               
```

However, the data within the `\url` portion, while it does render, it appears to just render as plain text (i.e. the `\url` portion appears to be stripped out; pictured below). Is there a way to enable hyperlink / `\url` functionality?

![image](https://user-images.githubusercontent.com/8325672/127000183-14b80f1e-c4bf-493a-9df4-5540bf110d67.png)

While browsing through the documentation, [I found a link](
https://sphinxcontrib-bibtex.readthedocs.io/en/latest/api/transforms.html) that seems to indicate this functionality is supported, but I'm not familiar with what is needed to enable this functionality. Also, with the latest version being `2.3.1a0`, but the latest available version I can pull via `pip3` on Ubuntu 20.04 being `2.3.0`, I wanted to ask if I just need to manually build/deploy `2.3.1a0` and I'll automatically have this functionality.

Thank you for your time and assistance, and thanks for building + maintaining this awesome tool!

**Comment by mcmtroffaes** [comment]
Thanks for reporting. This should work out of the box... I'm not sure why it's not working. I'll investigate in more detail as soon as I find some time.

**Comment by mcmtroffaes** [comment]
I've figured out the problem. pybtex has changed the way it is parsing fields, and this is breaking the conversion. I think it's probably better to fix this on the pybtex end; it has a hyperref node already which sphinxcontrib-bibtex could simply pick up.
