### ISSUE TITLE
Lord Rayleigh

### ISSUE THREAD

**Issue by mforbes** [mcmtroffaes/sphinxcontrib-bibtex#263]
It turns out that citing papers by Lord Rayleigh is quite a challenge with BibTeX.  Here are a couple of suggestions, neither of which works out of the box with `sphinxcontrib-bibtex`.  Any suggestions for a solution?

* https://texfaq.org/FAQ-bibprefixsort

  Recommends definining something like the following to sort differently than displayed:

  ```BibTeX
  @preamble{ {\providecommand{\noopsort}[1]{}} }
  @article{Rayleigh:1882,
	  author = "{\noopsort{Rayleigh}}{Lord Rayleigh}",
	  doi = {10.1080/14786448208628425},
	  eprint = {https://doi.org/10.1080/14786448208628425},
	  journal = {The London, Edinburgh, and Dublin Philosophical Magazine and Journal of Science},
	  number = {87},
	  pages = {184-186},
	  publisher = {Taylor & Francis},
	  title = {On the equilibrium of liquid conducting masses charged with electricity},
	  volume = {14},
	  year = {1882}}
  ```

  This relies on LaTeX being able to process the `\noopsort` command, which I don't see a good way of making work in the Sphinx context.  (Though this is my preferred solution as it allows me to use journal-defined bst files.)

* https://tex.stackexchange.com/questions/147932/peerage-titles-in-the-author-field-in-bibtex

  Recommends redefining the style to support a `nameaddon` field:
  ```BibTeX
  @article{Rayleigh:1882,
          author = {Strutt, John William},
          nameaddon = {3rd Baron Rayleigh},  % Or {Lord Rayleigh}
	  doi = {10.1080/14786448208628425},
	  eprint = {https://doi.org/10.1080/14786448208628425},
	  journal = {The London, Edinburgh, and Dublin Philosophical Magazine and Journal of Science},
	  number = {87},
	  pages = {184-186},
	  publisher = {Taylor & Francis},
	  title = {On the equilibrium of liquid conducting masses charged with electricity},
	  volume = {14},
	  year = {1882}}
  ```

The second could probably be made to work by customizing the style (have not tried that yet).  Is there another option that might be preferable?

**Comment by mcmtroffaes** [comment]
Whatever the solution be, this would require some changes to pybtex, as that's essentially responsible for all bibtex entry formatting. I've forwarded your issue on the pybtex issue tracker:

https://bitbucket.org/pybtex-devs/pybtex/issues/155/support-non-standard-name-formats-such-as

**Comment by mforbes** [comment]
Thanks for forwarding this.  I have not yet isolated `pybtex` behaviour from the whole Sphinx system.

**Comment by mcmtroffaes** [comment]
Sure, no problem at all!

**Comment by mcmtroffaes** [comment]
Closing as this is a purely upstream issue.
