### ISSUE TITLE
"Warning: duplicate citation for key" if using reference twice

### ISSUE THREAD

**Issue by PrometheusPi** [mcmtroffaes/sphinxcontrib-bibtex#271]
I use *sphinxcontrib-bibtex* to cite references throughout our documentation but define them only once in a `*.bib` file. 
However, if I reference the same paper in two different pages, I get the following warning:
```bash
/...picongpu/docs/source/usage/plugins/radiation.rst:536: WARNING: duplicate citation for key "Pausch2019"
/.../picongpu/docs/source/install/path.rst:64: WARNING: duplicate citation for key "Pausch2019"
```

Is this intended and is there a way to avoid this warning?

**Comment by mcmtroffaes** [comment]
Do you have more than one bibliography directive? If so, yes, you'll get duplicate citation warnings as each citation is meant to occur only once. Multiple citation references to the same citation should work though.

**Comment by PrometheusPi** [comment]
Thank you @mcmtroffaes for your very quick answer. 
Yes, I use multiple *bibliography directive* by calling 
```
.. bibliography::
   :cited:
```
on every page where a citation occurs in order to get a literature collection for the specific topic the page covers. 

The multiple citation to the references works fine and point only to the link on the same page. (Only if I remove the bibliography directive on that page, the link points to another page.) 
Will  *sphinxcontrib-bibtex* always prefer pointing to a local bibliography directive instead of to one on another page?

**Comment by mcmtroffaes** [comment]
The bibliography directive collects all citations cited across all documents, as it uses the standard sphinx citation system and that's set up in that way by upstream sphinx. You can only have one document containing

```
.. bibliography::
   :cited:
```

which will then bundle all citations.

If you want one bibliography per page, then I suggest using the footnote system with the footcite role and footbibliography directive. The sphinx footnote system works per page. Also see https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#local-bibliographies for more options.

> Will _sphinxcontrib-bibtex_ always prefer pointing to a local bibliography directive instead of to one on another page?

There's no guarantee.

**Comment by PrometheusPi** [comment]
Thanks @mcmtroffaes for you help - I will close the issue now.

**Comment by mcmtroffaes** [comment]
You're welcome @PrometheusPi - glad I could help!
