### ISSUE TITLE
Enumerated lists in reverse order?

### ISSUE THREAD

**Issue by matthewfeickert** [mcmtroffaes/sphinxcontrib-bibtex#272]
Hi. :wave: Thanks for making and maintaining `sphinxcontrib-bibtex`! I see that in [`v0.2.4+` there are enumerated lists](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#bullet-lists-and-enumerated-lists) as an option

```
.. bibliography::
   :list: enumerated
   :all:
```

I'm planning to use this in https://github.com/scikit-hep/pyhf/pull/1615 but I was wondering if there is some way that I'm missing to have the enumeration happen in reverse? That is have

![reverse](https://user-images.githubusercontent.com/5142394/135591711-a8f5270e-fc1a-4ebc-908d-1dacea9b4acb.png)

(which continue to citation number 23) be numbered 23, 22, 21.

I assume the answer is no, given that the docs mention that

> The start can be any positive integer (1, 2, 3, …) 

but I thought I'd ask just to make sure.

**Comment by mcmtroffaes** [comment]
It seems html ordered lists can have a "reversed" attribute that could be used for this: https://www.w3schools.com/tags/att_ol_reversed.asp However, docutils does not appear to support it... https://docutils.sourceforge.io/docs/ref/doctree.html#enumerated-list so indeed I fear the answer is indeed that it cannot be implemented within docutils... But if you know of a way, I'd be interested to learn!

**Comment by matthewfeickert** [comment]
Thanks for the fast response and the links! This information is helpful. :+1: 

As it seems that there isn't any solution in the near term (given docutils isn't going to change anything for a long time) I'm going to close this Issue.

**Comment by mcmtroffaes** [comment]
Sure. I'd be very happy to revisit this in the future if there would be a simple solution.

**Comment by tdegeus** [comment]
Are there any developments on this? 

I would like to show references as a list in chronological order with the newest on top. Then, inverting the numbering would ensure that the 'label' of each publication is preserved when newer publications are added

**Comment by mcmtroffaes** [comment]
The solution to this is to override the default labelling and sorting algorithms for whichever style you are using. Documentation of pybtex is slightly sparse but you can look at the source files of the original labelling and sorting plugins; the source is quite simple and easy to understand. Some examples to get started can be found in the sphinxcontrib-bibtex documentation here:

https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#custom-formatting-sorting-and-labelling

Does this help?

**Comment by tdegeus** [comment]
Yes! Thanks a lot.

I used:
```python
import pybtex.plugin
from pybtex.style.formatting.unsrt import Style as UnsrtStyle
from pybtex.style.labels import BaseLabelStyle

class MyPublicationsLabelStyle(BaseLabelStyle):
    def format_labels(self, sorted_entries):
        for i, entry in enumerate(sorted_entries):
            yield str(len(sorted_entries) - i)

class MyPublications(UnsrtStyle):
    default_label_style = MyPublicationsLabelStyle

pybtex.plugin.register_plugin("pybtex.style.formatting", "mypublications", MyPublications)
```

**Comment by mcmtroffaes** [comment]
Looks great, well done!

**Comment by mcmtroffaes** [comment]
Sorry for the slow response. My best guess is that you might be able to do something through the css style. But I'm not sure. To get perfect alignment, the labels and entries ought to be formatted in a html table, and I don't think sphinx currently does that for citations... Indeed it can look a bit messy if you have labels of very different lengths, at least in vanilla styles.

I'm sorry I can't be more helpful!
