### ISSUE TITLE
Citation node in document tree should a body element rather than an inline element

### ISSUE THREAD

**Issue by rappdw** [mcmtroffaes/sphinxcontrib-bibtex#273]
A failure occurs when attempting to build a pdf document from Sphinx using rinohtype. (See [brechtm/rinohtype issue #298](https://github.com/brechtm/rinohtype/issues/298#issuecomment-933597353)). In response to the issue reported against Rinohtype, Brecht Machiels responded:

> I think this is a bug in sphinxcontrib-bibtex... The citation node [of the document tree produced] is a child of a paragraph, while the docutils specification lists citation as a [body element](https://docutils.sourceforge.io/docs/ref/doctree.html#body-elements), not an inline element. To fix this, the wrapping paragraph should be eliminated. For reference, look at the output of rst2pseudoxml.py (included with docutils) on a [citation defined in plain reStructured](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#citations) ... 

While some sphinx extensions are forgiving of not following docutils specification precisely, Rinohtype (and perhaps others?) are not.

I have a git repo that reproduces the issue encountered [https://github.com/rappdw/rinoh_error](https://github.com/rappdw/rinoh_error).

When run from the repo: 
`make html` produces expected results
`make rinoh` results in an error

**Comment by mcmtroffaes** [comment]
Thanks for reporting. I'm amazed nobody tripped on this before, as this has been the structure for many years now! Should be fairly easy to fix, and the only question is how.

Is there any particular compound body element that would be suitable for containing the citation nodes? I'm guessing "compound" although it's not documented: https://docutils.sourceforge.io/docs/ref/doctree.html#compound If you have a better suggestions please do speak up.

The other option is not to have anything, but then the bibliography cannot be referenced, and someone might be relying on this.

**Comment by rappdw** [comment]
I'm afraid I don't have a good suggestion. I'm not terribly familiar with the docutil spec and am mostly relaying info provided by @brechtm (author of Rinohtype).

**Comment by brechtm** [comment]
> Is there any particular compound body element that would be suitable for containing the citation nodes? I'm guessing "compound" although it's not documented: https://docutils.sourceforge.io/docs/ref/doctree.html#compound If you have a better suggestions please do speak up.

The [container](https://docutils.sourceforge.io/docs/ref/rst/directives.html#container) is probably better suited. The directives documentation that links to provides some documentation for the nodes, thankfully.

**Comment by mcmtroffaes** [comment]
Oh great, thanks for the suggestion @brechtm! Looks perfect for this purpose. I'll look at updating the PR with that in the next few days, and will also try to fix the remaining issues with it.
