### ISSUE TITLE
missing backrefs when using numpydoc

### ISSUE THREAD

**Issue by ragonneau** [mcmtroffaes/sphinxcontrib-bibtex#277]
I am currently building a documentation that uses sphinxcontrib-bibtex (v2.4.1, with sphinx v4.2.0 and numpydoc v1.1.0), but the bibliography does not contain back-references to the citations in the documentation (as in plain RST when the reference has not been cited). It is neither surrounded by brackets. I set my conf. py as
```
extensions.append('sphinxcontrib.bibtex')
bibtex_bibfiles = ['_static/refs.bib']
bibtex_encoding = 'latin'
bibtex_default_style = 'plain'
bibtex_bibliography_header = ".. rubric:: References"
```

My RST source file is
```
<text> :cite:`my-ref` <text>

.. bibliography::
```

Is it an expected behavior? If yes, how can I add those references (that do appear using :footcite:`my-ref` and .. footbibliography::).

Thank you,
Tom.

**Comment by ragonneau** [comment]
Hi @mcmtroffaes, I was wondering whether you had any time to look into this issue yet? My documentation is online, you can see the above-mentioned file [here](https://cobyqa.readthedocs.io/en/latest/algo/linalg.nnls.html).

Thank you in advance,
Tom.

**Comment by mcmtroffaes** [comment]
Yeah, sorry about the long delay @ragonneau - I tried a while back but didn't find the cause immediately. In the meantime, some more urgent things have put this behind on schedule. It's definitely still on my radar.

**Comment by ragonneau** [comment]
No worries @mcmtroffaes, I wanted to make sure that this issue did not fall into oblivion.

**Comment by mcmtroffaes** [comment]
Got this reproduced now. Still don't know where the cause is however.

**Comment by mcmtroffaes** [comment]
I've given this a stab again, and it looks like numpydoc removes the backrefs prematurely here:

https://github.com/numpy/numpydoc/blob/6e748efc6b90ff29ddfbc1334c2ac7197ad67858/numpydoc/numpydoc.py#L146

**Comment by mcmtroffaes** [comment]
I've posted a fix upstream. You can use this branch of numpydoc if you already want to test this:

https://github.com/mcmtroffaes/numpydoc/tree/feature/fix-inline-backrefs

**Comment by mcmtroffaes** [comment]
The fix has now been merged upstream.

**Comment by ragonneau** [comment]
Thank you very much for working on that matter :grin: This will be very helpful, as I now have several projects using `sphinxcontrib-bibtex`.

Cheers,
Tom.

**Comment by mcmtroffaes** [comment]
You're welcome, glad I could (finally!!) help.
