### ISSUE TITLE
Test reference in jupyter notebook

### ISSUE THREAD

**Issue by pifparfait** [mcmtroffaes/sphinxcontrib-bibtex#278]
Hi, 
I just installed sphinxcontrib-bibtex from using pip install sphinxcontrib-bibtex, but I wanted to test if it works, and I don't know how to try it. 
I'm now after python setup.py install. 

And when I try to cite from the following Minimal Example, I don't get the expected outcome. So I think that I don't know how to test it. @mcmtroffaes any help or recommendation?

The example:
See :cite:t:`1987:nelson` for an introduction to non-standard analysis.
Non-standard analysis is fun :cite:p:`1987:nelson`.

.. bibliography::

The output is: 
See :cite:t:1987:nelson for an introduction to non-standard analysis. Non-standard analysis is fun :cite:p:1987:nelson.

.. bibliography::
Many thanks
Parfait

**Comment by mcmtroffaes** [comment]
You can find all the files for a minimal example here: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/tree/develop/test/roots/test-debug_minimal_example I hope this helps.

**Comment by pifparfait** [comment]
I used them in the same project but, I don't have the correct answer. Do I do any specific thing?

**Comment by mcmtroffaes** [comment]
I checked and running sphinx on this minimal test project gives me the expected results for the html builder:

```
> cd test/roots/test-debug_minimal_example/
> sphinx-build . _build/ -b html
Running Sphinx v4.1.2
making output directory... done
checking bibtex cache... out of date
parsing bibtex file ******\sphinxcontrib-bibtex\test\roots\test-debug_minimal_example\refs.bib... parsed 1 entries
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build.
```

After running this, ``_build\index.html`` contains the expected result. I hope this helps. If these exact steps don't work for you, please provide a full error log, and I'll happily investigate.

**Comment by pifparfait** [comment]
Many thanks, @mcmtroffaes  What you tell me if that works. I was expecting the output in the notebook, not in the Html. What I'm wxpecting is possible to achieve?

**Comment by mcmtroffaes** [comment]
I'm very sorry but I fear I can't help you with how to work with jupyter notebook, as I have no experience with it. However, if the html instructions work, then the problem is likely not with sphinxcontrib-bibtex. I suggest asking the jupyter folks for help with your problem. Stackoverflow also has a jupyter-notebook tag which might be helpful: https://stackoverflow.com/questions/tagged/jupyter-notebook

**Comment by pifparfait** [comment]
Many thanks @mcmtroffaes! Let's close this. Take care!
