### ISSUE TITLE
Pybtex version update

### ISSUE THREAD

**Issue by 0phoff** [mcmtroffaes/sphinxcontrib-bibtex#280]
The [requirements of your package](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/develop/requirements.txt#L3) state that you need `pybtex>=0.20`.
However, when using this package with `pybtex 0.21`, my code crashes with the following exception:
```
Extension error (sphinxcontrib.bibtex.domain):
Handler <function env_updated at 0x7fa895ad3048> for event 'env-updated' threw an exception (exception: 'Style' object has no attribute 'format_entry')
```

I updated `pybtex` to the newest 0.24 version, and everything seems to be running fine now, so I guess you might have forgotten to update your dependencies ? Not sure which minimal version is required, so that needs some more testing.

**Comment by mcmtroffaes** [comment]
Ah, thanks for raising this. Looks like the requirements are slightly outdated - I'll update them.

**Comment by mcmtroffaes** [comment]
Fixed in develop. Thanks again for reporting.
