### ISSUE TITLE
option to disable or tweak tooltips

### ISSUE THREAD

**Issue by mcmtroffaes** [mcmtroffaes/sphinxcontrib-bibtex#286]
See https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/198#issuecomment-1030160131

**Comment by Jellby** [comment]
This is my use case (I'm working on updating this to more up to date versions, but I guess you'll see the point).

Extension to (among other things) render math in titles as MathJax:
https://gitlab.com/Molcas/OpenMolcas/-/blob/master/doc/extensions/molcasbib.py

HTML result:
https://molcas.gitlab.io/OpenMolcas/sphinx/references.html

You'll see some of these titles won't be very nicely rendered in plaintext (e.g. 189). Ideally, the tooltip would use the fully rendered (with MathJax) version, but I assume that's not easy. My preferred solution would be using an alternative citation style for the tooltips only, in this second style I'd disable the titles (and probably use first-name initials and no doi).

**Comment by mcmtroffaes** [comment]
This is now implemented in develop. Thanks again @Jellby for your useful suggestion!

**Comment by Jellby** [comment]
Looking forward to having it in a release, so I can use it in production code...
