### ISSUE TITLE
pre and post text in citations

### ISSUE THREAD

**Issue by RobertoBagnara** [mcmtroffaes/sphinxcontrib-bibtex#288]
Having found no documentation for pre and post text in citations, I have found test/roots/test-natbib/doc0.rst, which suggests the feature might be available.
However, even though my use cases seem to match perfectly, I get errors and the references are rendered as "[]".
In my rst file I have

:cite:t:`The-Label:2019 [Section 7.3.5]`
:cite:p:`The-Label:2019 [see][Section 7.3.5]`
:cite:`The-Label:2019 [Section 7.3.5][see]`
:cite:`The-Label:2019` (just to make sure the label is correct).

And the warnings are

/home/roberto/test/test.src:37: WARNING: could not find bibtex key "The-Label:2019 [Section 7.3.5]"
/home/roberto/test/test.src:37: WARNING: could not find bibtex key "The-Label:2019 [see][Section 7.3.5]"
/home/roberto/test/test.src:37: WARNING: could not find bibtex key "The-Label:2019 [Section 7.3.5][see]"

**Comment by RobertoBagnara** [comment]
I am not sure what you mean.  Perhaps it is not necessary because there are other ways of achieving the effect of LaTeX's \cite[text]{label}?  I use this very often in my documents, so if you can tell me how to do that I will be grateful.
Thanks!

**Comment by mcmtroffaes** [comment]
Well, it's not quite the same but one can always just write ``see :citet:`label`, Section 7.3.5``.

**Comment by RobertoBagnara** [comment]
Indeed, it is not quite the same and it can also result in ambiguity.
