### ISSUE TITLE
New root_doc variable is ignored.

### ISSUE THREAD

**Issue by jhmeinke** [mcmtroffaes/sphinxcontrib-bibtex#292]
With version 4.0 sphinx renamed `master_doc` to `root_doc`, but this is ignored by sphinxcontrib-bibtex.
If I use `root_doc` I get the following error message because `index.rst` does not exist.
```
extension error (sphinxcontrib.bibtex.domain):
Handler <function env_updated at 0x7f8b63b5f910> for event 'env-updated' threw an exception (exception: 'index')
```
If I replace `root_doc` with `master_doc` everything works fine.

Sphinx v4.4.0
sphinxcontrib-bibtex 2.4.1
Arch Linux

**Comment by mcmtroffaes** [comment]
Thanks for reporting! This should now be fixed in develop; the fix will be included with the next release.

**Comment by jhmeinke** [comment]
Thank you! That was amazingly fast!
