### ISSUE TITLE
Unable to apply standard formatting such as italics in title field

### ISSUE THREAD

**Issue by michaelosthege** [mcmtroffaes/sphinxcontrib-bibtex#300]
I have several references that have latin names in their titles, which by convention must be formatted _cursive_.

```bibtex
@article{someArticle,
  title = {Prediction of {E}scherichia~coli expression performance},
  ...
}
```

I tried a variety of formatting options, but none of them worked. Most were just not interpreted and copied into the output.

> `title = {Prediction of \textit{{E}scherichia~coli} expression performance},`
> `title = {Prediction of \\textit{{E}scherichia~coli} expression performance},`
> `title = {Prediction of {\textit{{E}scherichia~coli}} expression performance},`
> `title = {Prediction of $\textit{{E}scherichia~coli}$ expression performance},`
> ```title = {Prediction of `\textit{{E}scherichia~coli}` expression performance},```
> ```title = {Prediction of $`\textit{{E}scherichia~coli}`$ expression performance},```
> ```title = {Prediction of `$\textit{{E}scherichia~coli}$` expression performance},```

The `sphinxcontrib-bibtex` extension seems to be interpreting the `.bib` file in a different way than most other LaTeX environments.
All the answers I found on the internet did not work.

The only thing I got working are superscript characters on names of equally contributing first authors:

```bibtex
@article{someArticle,
  author = {FirstOne$^1$, Alice and
            FirstTwo$^1$, Bob and
            Third, Charlie}
}
```

------------

What are the interpretation rules with `sphinxcontrib-bibtex`?

Is it possible to use (LaTeX) formatting, and if so: how?

**Comment by mcmtroffaes** [comment]
Basically, LaTeX formatting in bib files isn't really supported by pybtex (beyond simple unicode/latex conversions, for convenience), and since sphinxcontrib-bibtex uses pybtex to parse and format bibtex entries, that limitation is carried over to the extension... I'm sorry that's not so helpful! But that's the state of affairs right now.

**Comment by michaelosthege** [comment]
Thanks for the quick response!

I'm under time pressure for my thesis..
Where am I on a scale from "_this is easy to fix in `pybtex`_" to "_you'll have to find & replace the words in the resulting `*.tex` file_"?

**Comment by mcmtroffaes** [comment]
Pretty much on the latter end, I'm afraid. Whilst pybtex is great at parsing the bibtex format, it doesn't parse LaTeX inside the bibtex entries beyond some obvious one-to-one translations of unicode characters, like $^1$. So you should be good with most if not all LaTeX code that represents unicode symbols, but not with things like custom formatting like \textit inside titles.

**Comment by mcmtroffaes** [comment]
This limitation is now clearly documented. I'm sorry that I couldn't be more helpful.

**Comment by michaelosthege** [comment]
@mcmtroffaes I wrote a `SphinxPostTransform` that runs after the `BibliographyTransform` to post-process the citation paragraphs to fix italics formatting. It could certainly be extended to fix other common formatting directives (`\texttt`, `\textbf`) too.

Shall I open a PR to add it to `sphinxcontrib.bibtex.transforms`?

**Comment by mcmtroffaes** [comment]
Thank you for trying to address this. What you say would be a temporary solution yes. Please share and I'll have a look.

A better (IMO) solution would be to teach pybtex about LaTeX e.g. via pylatexenc, which can correctly handle a very large collection of latex commands; in that way all consumers of pybtex can benefit from it. At the moment pybtex uses the latexcodec package (which I wrote), but this only handles unicode conversions.
