### ISSUE TITLE
LaTeX output generates an extra “Bibliography" title 

### ISSUE THREAD

**Issue by fcarvalhopacheco** [mcmtroffaes/sphinxcontrib-bibtex#301]
Hi @mcmtroffaes, 

I am still getting two `Bibliography` titles on my `Table of contents`. Please [see the full pdf here](https://whots-annual-report.readthedocs.io/_/downloads/whots16-data-report/en/latest/pdf/). I tried many things, including [Mismatch Between Output of HTML/Text and LaTeX Backends](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#mismatch-between-output-of-html-text-and-latex-backends).

My `index.md` is [here](https://github.com/hot-dogs/whots16-data-report/blob/main/docs/source/index.md)
My `references.md` is [here](https://github.com/hot-dogs/whots16-data-report/blob/main/docs/source/references.md). 
- You will notice I am using markdown (myst-parser) for this project. I tried to follow your conversation by doing 
````
```{eval-rst}
.. raw:: latex

   \cleardoublepage
   \begingroup
   \renewcommand\chapter[1]{\endgroup}
   \phantomsection

.. _refs:

References
==========

.. bibliography::
```
````

My `conf.py` is [here](https://github.com/hot-dogs/whots16-data-report/blob/main/docs/source/conf.py)
- You will notice that my [`preamble`](https://github.com/hot-dogs/whots16-data-report/blob/f081c79ecaf460b050f12d3c9506cdf0b6e0efa4/docs/source/conf.py#L121)  calls [`mystyle.sty`](https://github.com/hot-dogs/whots16-data-report/blob/f081c79ecaf460b050f12d3c9506cdf0b6e0efa4/docs/source/latex_templates/mystyle.sty) file.
- I also tried different `preamble` approaches. [See here](https://github.com/hot-dogs/whots16-data-report/blob/f081c79ecaf460b050f12d3c9506cdf0b6e0efa4/docs/source/latex_templates/mystyle.sty#L124)

## Some notes:
1. I was getting 2 `table of contents` title as well. That problem was solved by adding the following 
` 'tableofcontents': ' ',` on my `conf.py` file. [See here](https://github.com/hot-dogs/whots16-data-report/blob/f081c79ecaf460b050f12d3c9506cdf0b6e0efa4/docs/source/conf.py#L138).  My`conf.py` was adapted from [this documentation](https://sphinxguide.readthedocs.io/en/latest/sphinx_basics/settings.html)

2. I wonder if there is something like  `'bibliography': ' ', ` as well.  

3. I am afraid that my [`maketitke.sty`](https://github.com/hot-dogs/whots16-data-report/blob/f081c79ecaf460b050f12d3c9506cdf0b6e0efa4/docs/source/latex_templates/maketitle.sty) file could be creating that as well... Not sure. Please,  check the very end of that file [here](https://github.com/hot-dogs/whots16-data-report/blob/f081c79ecaf460b050f12d3c9506cdf0b6e0efa4/docs/source/latex_templates/maketitle.sty#L132).

4. The following code cannot be used for `references.md`. Sphinx needs a title for each file, which should be 
`# References` or `# Bibliography`; otherwise, many WARNINGS are displayed. Furthermore, the code just removes the title from from the `table of contents`, and doesn't solve the dual `Bibliography` problem.

```` 
```{eval-rst}
.. only:: html or text

   .. rubric:: References

.. bibliography::
```
````

## Similar Issues
#48 ,[#1523 ](https://github.com/executablebooks/jupyter-book/issues/1523), [sphinx.sty#L515](https://github.com/saezlab/data_tools/blob/afbd3799771edaa4ffb5a5a9a53395169e728b79/docs/latex/sphinx.sty#L515)

---

Any thoughts would be much appreciated!

---

**Comment by mcmtroffaes** [comment]
Hi @fcarvalhopacheco - apologies for leaving this so long. This is a problem with sphinx not generating consistent output between latex and html. This happens whether or not the extension is used. This sphinx issue might be related: https://github.com/sphinx-doc/sphinx/issues/4775

**Comment by mcmtroffaes** [comment]
I'll close this as it is a known and documented upstream bug. I've added a link to the relevant issue in the documentation, as there is at least one more workaround discussed there, which could be useful to users.
