### ISSUE TITLE
The \url{...} shows up in the link title (shown at mouse hover)

### ISSUE THREAD

**Issue by 1kastner** [mcmtroffaes/sphinxcontrib-bibtex#305]
In my bibliography, I have several links, quite similar to https://github.com/mcmtroffaes/sphinxcontrib-bibtex/pull/259. They also work perfectly for me. However, a minor issue remains: A `url` shows up in front of the link when I use the mouse hover. Is it possible to remove that small text block?

![grafik](https://user-images.githubusercontent.com/5236165/180037513-bf27e91e-517b-4c04-899b-7e3287bfc8e9.png)

The browser inspector shows this as the link title: `Bay generator. \url https://sites.google.com/site/gciports/premarshalling-problem/bay-generator, 2022. Accessed: 2022-07-20.`.

The used bibtex entry was:
```
@online{exposito2012marshalling-software,
    title = {Bay Generator},
    howpublished = {\url{https://sites.google.com/site/gciports/premarshalling-problem/bay-generator}},
    note = {Accessed: 2022-07-20},
    year = {2022}
}
```

Or is the issue actually located at pybtex?

**Comment by mcmtroffaes** [comment]
Thanks for reporting. There's some processing of the \url command that happens at the sphinxcontrib-bibtex level as pybtex doesn't deal with this LaTeX command. I'll see if I can fix this for the tooltips.

**Comment by 1kastner** [comment]
First of all thanks to you to maintain the package!

**Comment by 1kastner** [comment]
Thanks for the quick fix!

**Comment by mcmtroffaes** [comment]
You're most welcome.
