### ISSUE TITLE
Document markdown `myst` usage

### ISSUE THREAD

**Issue by jacopok** [mcmtroffaes/sphinxcontrib-bibtex#310]
Hello, I've tried using this extension in conjunction with [`myst`](https://myst-parser.readthedocs.io/en/latest/) and it works well; for example, the effect of the rst command
```rst
:cite:p:`1987:nelson`
```
can be equivalently obtained in a markdown file as 
```markdown
{cite:p}`1987:nelson`
```

My guess is that this generalizes; it would be nice to briefly mention it in the README, since it's a simple thing but it might leave a user confused regarding the correct syntax (it did for me).

**Comment by mcmtroffaes** [comment]
Thanks, that's a great suggestion!

**Comment by mcmtroffaes** [comment]
Could you double check this example (to be added to the docs)?

```
    See {cite:p}`1987:nelson` for an introduction to non-standard analysis.

    ```{bibliography} references.bib
    ``` 
```

**Comment by mcmtroffaes** [comment]
Awesome, many thanks for the quick turnaround!
