### ISSUE TITLE
[ENH] use Path from pathlib internal

### ISSUE THREAD

**Issue by jonas-eschle** [mcmtroffaes/sphinxcontrib-bibtex#314]
Hi there, thanks a lot for this nice addon!

I would suggest to switch internal path manipulation to use `Path` from `pathlib`. This would prevent some bugs, such as whet specifying the .bib path as a `Path` object, that fails currently.

I can contribute this if you're fine with it

**Comment by mcmtroffaes** [comment]
Thanks for offering to help, I appreciate that! However, as far as I know, sphinx does not use pathlib internally (see https://github.com/sphinx-doc/sphinx/issues/10395). For consistency, let's migrate when Sphinx migrates as well; this appears to be planned for Sphinx 6.0.
