### ISSUE TITLE
ablog and bibtex reflow issue

### ISSUE THREAD

**Issue by warmstarter** [mcmtroffaes/sphinxcontrib-bibtex#318]
**Describe the bug**
When using ablog and bibtex together, it mostly renders ok, but the layout gets oddly varied by the size of the browser on a desktop/laptop when reflowing.

**To Reproduce**
You can see this on my blog:
https://tryst.eris.yoga/

On the left bar you will see 'About' 'Bibliography' and 'TdM Dictionary'
'About' and 'TdM Dictionary' behave properly, 'Bibliograhy' does not.

To see, click on these and then change the size of the browser.
'About' and 'TdM Dictionary' will reflow (I think that is the term) properly.
'Bibliography' only works with a very narrow window, and gets odd as you stretch it larger.

I imagine most people will have their window larger enough that 'Bibliography' is an immediate problem.
On a cellphone (at least mine), there is no issue.

I have created a github repository of my blog, so that you are able to see exactly what it is I am doing, which is nothing at all complex.
https://github.com/warmstarter/namelessblog

Please let me know if you have any questions that I can help with.

I understand this may not be solely (or at all) a bibtex issue, but instead an ablog issue.

I have opened a bug with ablog here to aid commnication:
https://github.com/sunpy/ablog/issues/164

**System Details**
Linux ip-172-26-15-157 4.19.0-20-cloud-amd64 https://github.com/sunpy/ablog/pull/1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux
Debian 10.13 (Completely updated)
Python 3.7.3-2
Virtualenv (see requirements.txt in included repository for more.)

**Installation method**
pip

**Comment by mcmtroffaes** [comment]
It looks like you're hitting the docutils bug reported here: #309 and https://validator.w3.org/nu/?doc=https%3A%2F%2Ftryst.eris.yoga%2Fbibliography%2F confirms a spurious ``</div>``. It's been reported and merged upstream; see https://sourceforge.net/p/docutils/patches/195/ You can try using an older docutils version, any 0.17.x version should still be good if I recall correctly. Alternatively you can try running an unreleased version of docutils from source that includes the patch, but your mileage might vary.

**Comment by warmstarter** [comment]
Thank you for the fast reply. I downgraded to docutils 0.17.1 and that solved the issue. I might try the newer version once it gets into an official release.
