### ISSUE TITLE
Implicit hyperlink in references

### ISSUE THREAD

**Issue by m3lab-zzl** [mcmtroffaes/sphinxcontrib-bibtex#321]
Hi, is it possible to add a hyperlink implicitly to a reference? Means that the url is not shown explicitly, but we can jump to certain webpages by a single click.

For example:
![image](https://user-images.githubusercontent.com/102862066/210310727-3d69358a-be99-470f-a2e3-f2e335fe343a.png)

Not this one:
![image](https://user-images.githubusercontent.com/102862066/210310249-63f73c10-6cb7-4923-9ff8-990531f3a2bc.png)

How can we achieve the first one? It would be perfect if you could provide a minimal example. Thank you in advance.

**Comment by mcmtroffaes** [comment]
Apologies for the time it's gotten me to this. But yes, you should be able to do something like this, by using a custom style. As a starting point you could use something along these lines (roughly based on https://bitbucket.org/pybtex-devs/pybtex/src/master/pybtex/style/formatting/unsrt.py; I've not tested this):

```
class MyStyle(UnsrtStyle):
    def get_article_template(self, e):
        volume_and_pages = first_of [
            # volume and pages, with optional issue number
            optional [
                join [
                    field('volume'),
                    optional['(', field('number'),')'],
                    ':', pages
                ],
            ],
            # pages only
            words ['pages', pages],
        ]
        url = field('url', raw=True)
        template = toplevel [ href(url) [
            self.format_names('author'),
            self.format_title(e, 'title'),
            sentence [
                tag('em') [field('journal')],
                optional[ volume_and_pages ],
                date],
            sentence [ optional_field('note') ],
        ] ]
        return template
```

**Comment by mcmtroffaes** [comment]
Oh, if not every entry has a url field you may have to experiment with the first_of and/or optional nodes to make it work. Note these templates are part of pybtex; they are documented here https://docs.pybtex.org/api/styles.html#template-language including relevant links to the code.

I'll close this as I think I've answered your question. Good luck!
