### ISSUE TITLE
Math in title not rendering 

### ISSUE THREAD

**Issue by m3lab-zzl** [mcmtroffaes/sphinxcontrib-bibtex#324]
Some academic papers have math symbols in the their titles, something looks like $\alpha$.

On the website that published them, the symbols seem to be rendered nice, but citing them in sphinx project with bibtex extension failed to produce the same result. Both for the built htmls and pdfs.

[minimaExample.zip](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/files/11136996/minimaExample.zip)

The Physical Review B website: https://journals.aps.org/prb/abstract/10.1103/PhysRevB.71.214307

The built html:
![image](https://user-images.githubusercontent.com/102862066/229476983-6e5f8420-8495-4995-bd3f-5441b53fcd09.png)

The built pdf:
![image](https://user-images.githubusercontent.com/102862066/229477265-83e06f4a-0dd6-4157-a9c4-b38dcee2b6b0.png)

**Comment by mcmtroffaes** [comment]
Thanks for reporting. The extension can do some very elementary latex to unicode conversions, but does not support full latex to html rendering. The workaround is to keep latex limited to simple symbols, supported by latexcodec which pybtex uses for this purpose in the background:

https://github.com/mcmtroffaes/latexcodec/

I understand this is probably not quite what you were hoping for, but I hope that you can edit your bib files to simplify the latex sufficiently so it can be rendered to html by pybtex. Does this help?

**Comment by m3lab-zzl** [comment]
I do not understand, how can I translate the equation to unicode tetx? Could you please provide an example?

I tried an online converter https://www.johndcook.com/unicode_latex.html, but it failed for the first symbol \mathrm{A}.

![image](https://user-images.githubusercontent.com/102862066/233546065-f2e10bff-8f04-4caf-bc3e-22675d8806cc.png)

**Comment by mcmtroffaes** [comment]
You can find a list of unicode symbols with corresponding latex code that latexcodec supports here: https://github.com/mcmtroffaes/latexcodec/blob/develop/latexcodec/table.txt The formula in the title from your specific reference does seem a bit too complicated for the codec unfortunately, in particular, the "1/2" in the subscript will likely pose a problem. The best you can do might look like AB'½B''½O₃ at best (which would require adding ½ as a symbol first, I don't think it's there yet). I'm sorry I can't be more helpful!

**Comment by drammock** [comment]
@m3lab-zzl note that `\mathrm` can simply be omitted by selecting the normal Roman characters A, B, and O. But @mcmtroffaes is probably right that the fraction in the subscript may be impossible to get. AFAICT there is no subscript solidus or fraction slash. The best I could do is 

AB′₁⁄₂B″₁⁄₂O₃

**Comment by m3lab-zzl** [comment]
@mcmtroffaes and @drammock, thank you both for your explanation.

I think the most simple way for me is to manually modify the built html file by adding math environment tags of `<span class="math notranslate nohighlight">(equations here\)</span>` 

![image](https://user-images.githubusercontent.com/102862066/233892088-dd05ae86-9495-43f5-ae42-34a1dac98d0a.png)

Refresh the page and now the browser can render the formula nicely. 

![image](https://user-images.githubusercontent.com/102862066/233892067-ab843b4c-8385-4dcc-923c-d11bb43fa107.png)

As for the PDF, replace the corresponding part and it can also render nicely.

![image](https://user-images.githubusercontent.com/102862066/233893072-02f2ef90-8d51-4f20-bfb3-f73bd464fda2.png)

![image](https://user-images.githubusercontent.com/102862066/233893050-5c22de20-53ef-4351-ba8d-34b212225878.png)

Since I have just several refs that contains equations, manually edit the source files may be a not-bad solution for me.

For the  sphinxcontrib-bibtex extension however, I suggest adding a function to detect math equations in the reference (by its $$ symbol), and do the replacement automatically. Unfortunately I am not familiar with the underlying class structure and thus it is too hard for me to raise a pull request though I would like to contribute.

**Comment by mcmtroffaes** [comment]
Pybtex handles math conversions through the latexcodec, so what you suggest is already (to some extent, i.e. it only works for specific common characters) supported. If you have missing individual math symbols, feel free to post an issue at https://github.com/mcmtroffaes/latexcodec/ Unfortunately full latex parsing is quite tricky and not supported by pybtex, and that limitation carries over to sphinxcontrib-bibtex.

With that, I think this issue can be closed?

**Comment by m3lab-zzl** [comment]
@mcmtroffaes, you were right, some math conversions have already been done. However, I was suggesting a different way. Instead of replacing with unicode characters, rendering them with MathJax support may be an alternative solution.

The above replacement I did actually requires math environment, i.e., `<script async="async" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>` line is required, which will be automatically added by sphinx-build if the main body contains at least one math equation.
![image](https://user-images.githubusercontent.com/102862066/236603514-c449f83a-7080-48ab-a1ea-0431ce86d8c8.png)

![image](https://user-images.githubusercontent.com/102862066/236603471-a0b064d9-3b7f-4390-a49a-ab6b2663d228.png)

Otherwise, we must deliberately add that line, and then replace the 1st `\$` with `<span class="math notranslate nohighlight">\(` and the 2nd `\$` with `\)</span>` and so on. Then the webpages will be rendered as expected.
