### ISSUE TITLE
sphinx-autoapi support

### ISSUE THREAD

**Issue by PhilippWillms** [mcmtroffaes/sphinxcontrib-bibtex#327]
I am grateful about the advantages of this package, which I consider mainly in appearing `sphinx` like LaTeX. But how to solve the following topic:

It would be helpful to also use the bib item keys in code comments on method signature level, so that they are correctly considered by `sphinx-autoapi`. Currently, a `:cite:p` directive is only translated in RST file, not in Python code comments.

The following workaround is fine, using decentralized References chapter on module level.
```
"""Module comment

References
------------
.. [Kallrath2002] Kallrath, J. (2002), Planning and scheduling in the process industry. OR Spectrum 24(3), 219-250.
"""
...
def method() -> Path:
    """Get path to the WK problem instance for Task 1 described in the attachment of the first official publication [Kallrath2002]_ ."""
```

**Comment by mcmtroffaes** [comment]
The autodoc extension definitely should work (it's part of the test suite), but I haven't used/tested autoapi. Is the problem you're experiencing exclusive to autoapi, or do you see similar problems with autodoc?

**Comment by mcmtroffaes** [comment]
So it's all working now? If there's something specific you had to do, please do report here; I'll see if I can then make a note about it in the docs.

**Comment by PhilippWillms** [comment]
Yes, it is working. However, the migration process back from `autoapi` to `autodoc` was a bit cumbersome. Maybe for the long-term development of this API here, it would be useful to be compatible with `autoapi`.

**Comment by mcmtroffaes** [comment]
Yup, I think it would be good to get that working. I'll reopen this to track progress.

**Comment by mcmtroffaes** [comment]
I've added a regression test for autoapi just now. It seems to be working fine. It's possible that it failed earlier due to a recent update to sphinx or to autoapi? Either way, you can find the test example here:

https://github.com/mcmtroffaes/sphinxcontrib-bibtex/tree/develop/test/roots/test-autoapi

Thanks again for reporting!
