### ISSUE TITLE
.. bibliography :: extra <\div>

### ISSUE THREAD

**Issue by jessdtate** [mcmtroffaes/sphinxcontrib-bibtex#338]
calling `.. bibliography ::` seems to generate an extra `<\div>` in the html that is only visible when it is placed in the middle of the page.  The result is that any context after a bibliography section is stripped of formatting.

**Comment by mcmtroffaes** [comment]
Thanks for reporting. What is your version of docutils?

**Comment by jessdtate** [comment]
I've updated docutils to version 0.20, which seems to have fixed this issue

**Comment by mcmtroffaes** [comment]
That makes sense; this is a well documented bug (see for instance #309). I'm glad it's working for you now.
