### ISSUE TITLE
Support for docutils >=0.18

### ISSUE THREAD

**Issue by abhinavnatarajan** [mcmtroffaes/sphinxcontrib-bibtex#339]
Is there support planned for docutils versions 0.18 and above? I'm using sphinx version 7.2, which is incompatible with lower versions of docutils and for various workflow reasons it is difficult to use an earlier version of sphinx.

**Comment by mcmtroffaes** [comment]
The latest version of docutils should work just fine. However, don't use 0.18 or 0.19 since those are known to generate invalid html.
