### ISSUE TITLE
truncate authors option

### ISSUE THREAD

**Issue by casperdcl** [mcmtroffaes/sphinxcontrib-bibtex#340]
suggestion:

```rst
.. bibliography
   :max_authors: 5
   :author_overflow: et al.  <!-- or "and others", etc... -->
```

so that things with hundreds of authors[^1] don't hog the page :)

[^1]: https://arxiv.org/abs/2206.04615

**Comment by mcmtroffaes** [comment]
As a design philosophy for the plugin, all formatting of the entries themselves is left to pybtex (and fully customizable via pybtex styles), whereas the embedding of those formatted entries is handled by the extension.

So, you can achieve the behaviour that you describe with a small amount of coding, by adjusting the way pybtex formats the names, through a custom style. See https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#custom-formatting-sorting-and-labelling

For your use case, I suggest overriding the unsrt class, overriding the format_names function: https://bitbucket.org/pybtex-devs/pybtex/src/2b82780b5090b1c3de0875617b782fbb5b74ba4e/pybtex/style/formatting/unsrt.py#lines-46

I hope this helps. Good luck!

**Comment by mcmtroffaes** [comment]
Very nice! Mind if I add this as an example to the documentation, and/or try to get this included with upstream pybtex?

**Comment by casperdcl** [comment]
sure. Note that I never bothered to work out how to expose `max_names` config in rst though :)

**Comment by mcmtroffaes** [comment]
Swell! And yes, that's a global limitation currently of the way the plugin interfaces with pybtex: there is no consistent system to pass pybtex style parameters as rst directive options/flags, besides just inheriting a style and giving it a new name, as you have. From a usability perspective, it'd make sense to expose some more options that could be passed down from directive flags/options. However all styles will have their own parameters...
