### ISSUE TITLE
Allow missing field

### ISSUE THREAD

**Issue by tdegeus** [mcmtroffaes/sphinxcontrib-bibtex#341]
I have 'misused' book for a conference presentation. Consider a bib-file
```bib
@book{conference_deGeus2023_2,
  title = {Criticality and Nucleation of Slip at the Frictional Interface},
  author = {{de Geus}, T.W.J.},
  year = {2023},
  series = {Swiss Soft Days},
  number = {SSD 31},
  address = {{Fribourg, Switzerland}},
  url = {https://swisssoftdays.ethz.ch}
}
```

I include this bib-file as follows
```rst
.. bibliography:: library_conferences.bib
    :style: unsrt
    :list: enumerated
    :all:
```

Now 
```none
$ make html
.../conferences.rst:8: WARNING: missing publisher in conference_deGeus2023_2
```
and even worse, the output:
![bug](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/assets/7030445/b409f09d-48b4-473b-9b84-2fd8de2d81ca)

How can I simply get an output without publisher?

**Comment by mcmtroffaes** [comment]
The short answer is that it is a required field, so the error is expected:

https://www.bibtex.com/e/book-entry/

However, if you want to implement a style that does not conform to the bibtex standard, you can do so via pybtex, which is responsible for the actual formatting. Specifically, If you want to change the formatting and for instance allow certain missing fields, you can for instance subclass unsrt to adjust the formatting of book entries without publisher. See https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#custom-formatting-sorting-and-labelling for some examples and more details. I hope this helps!

**Comment by tdegeus** [comment]
Thanks. In the end it is pretty simple indeed with `pybtex`. 

When I started playing around I did come across [this bug](https://bitbucket.org/pybtex-devs/pybtex/issues/152) that seem to be solved. However, the latest release dates from 2021. Do you know if it is still maintained?

**Comment by mcmtroffaes** [comment]
Glad I could help. Pybtex hasn't seen a release for quite some time indeed; your guess is as good as mine...
