### ISSUE TITLE
Bibliography header repetition

### ISSUE THREAD

**Issue by ragonneau** [mcmtroffaes/sphinxcontrib-bibtex#342]
Hi @mcmtroffaes,

Let me first thank you again for your lovely package. It is very handy for each of my projects!

The `bibtex_bibliography_header` seems repeated at each compilation of my projects. I set in `conf.py`:

```python
bibtex_bibliography_header = """.. only:: html or text

    .. rubric:: References
"""
```

I compile my documentation several times, after incremental updates, and I obtain the following:

<img width="758" alt="Screenshot 2024-01-08 at 11 04 37 AM" src="https://github.com/mcmtroffaes/sphinxcontrib-bibtex/assets/33006763/23a66570-a2f1-4365-bbaa-612e3314ce30">

This is not a big problem, as my online documentation is always compiled from scratch. I just wonder whether this can create some troubles for some users.

Cheers,
Tom.

**Comment by mcmtroffaes** [comment]
Thanks for reporting this bug! I'll see if I can reproduce and fix this. Looking at the code, it looks like at this line:

https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/develop/src/sphinxcontrib/bibtex/domain.py#L314

right after ``if header:`` I might need to insert a line

```
self.data["bibliography_header"] = docutils.nodes.container()
```

This shouldn't be needed from the docs, but maybe Sphinx does something weird with caching when recompiling... If you could test to see if this fixes the problem that would be great. If not, it's also fine, I'll eventually get around to it myself.

**Comment by ragonneau** [comment]
Hi @mcmtroffaes,

I will try it this week, and I will let you know.

Cheers,
Tom.

**Comment by mcmtroffaes** [comment]
Brilliant, thanks so much!

**Comment by ragonneau** [comment]
As I mentioned in your PR, it works perfectly on my side. Thanks!

**Comment by mcmtroffaes** [comment]
Fantastic, thank you for confirming so quickly. I'll have the patch out for release shortly.

**Comment by ragonneau** [comment]
Splendid, thank you so much!
