### ISSUE TITLE
Cannot import due to `pkg_resources` on Python 3.12

### ISSUE THREAD

**Issue by LecrisUT** [mcmtroffaes/sphinxcontrib-bibtex#345]
For anyone who is recently finding issues using this extension, the issue is with `pybtex` [^1]. I don't have a bitbucket account to make some noise or submit a fix there, so if anyone who has, it would be appreciated to ping them and mention the affected projects.

[^1]: https://bitbucket.org/pybtex-devs/pybtex/issues/169/replace-pkg_resources-with

**Comment by drammock** [comment]
I'm the one who opened that issue on bitbucket. As you saw, it got basically zero traction (I even attempted to refactor the code to fix it, but ran out of time, and nobody has picked up where I left off nearly 9 months ago).  IMO pybtex is now *unmaintained* and I would encourage @mcmtroffaes to seek an alternative if possible.

**Comment by mcmtroffaes** [comment]
I feared this day might happen. From pybtex, I need the parser but also the template engine. Changing the template engine unfortunately will cause a massive API breakage, though maybe there are ways we can ease the transition. Coincidentally I started writing a template engine https://github.com/mcmtroffaes/rite a while ago though I've not used it anywhere as it was more of an internal experiment at the time.

[python-bibtexparser](https://github.com/sciunto-org/python-bibtexparser) looks promising.

**Comment by mgeier** [comment]
As a work-around, installing `setuptools` seems to make the error go away, as mentioned in https://bitbucket.org/pybtex-devs/pybtex/issues/169/replace-pkg_resources-with#comment-66140478.

**Comment by maxnoe** [comment]
`pkg_resources` is packaged together with bibtex, you should have `setuptools` in your runtime dependencies if you use it.

Python versions pre 3.12 always installed setuptools into new virtual environments, which is the reason why it mostly worked before.

You should also consider replacing usage of `pkg_resources` with `importlib.metadata` and `importlib.resources`.

**Comment by LecrisUT** [comment]
@maxnoe This is not an issue that `sphinxcontrib-bibtex` can handle because the issue originates in [`pybtex`](https://bitbucket.org/pybtex-devs/pybtex/issues/169/replace-pkg_resources-with). I do not have an account there to proposed fixes, nor did I have the time to write up a patch to use `importlib.metadata`. If a patch file can be provided for anyone with bitbucket account, that would be much useful.

**Comment by maxnoe** [comment]
You can add `setuptools` to your runtime dependencies to fix the issue for your users

**Comment by njzjz** [comment]
> You can add `setuptools` to your runtime dependencies to fix the issue for your users

It looks pybtex is dead (per [commit history](https://bitbucket.org/pybtex-devs/pybtex/commits/)), so I agree with this idea.

**Comment by LecrisUT** [comment]
Fair points, @mcmtroffaes are you okay with this approach?

**Comment by flying-sheep** [comment]
At this point, they fully migrated away from pkg_resources, but still didn’t make a release.

**Comment by mcmtroffaes** [comment]
I've added setuptools as a dependency for Python 3.12 (though this really belongs in pybtex...), so at least users should no longer hit this from the next release onward.

**Comment by kdeldycke** [comment]
@mcmtroffaes any plan for a `sphinxcontrib-bibtex` release? 🤗

**Comment by mcmtroffaes** [comment]
Sure, please do feel free to give it a spin in the meantime - a prerelease wheel/sdist can be found on testpypi: https://test.pypi.org/project/sphinxcontrib-bibtex/#history

**Comment by kdeldycke** [comment]
> Sure, please do feel free to give it a spin in the meantime - a prerelease wheel/sdist can be found on testpypi: https://test.pypi.org/project/sphinxcontrib-bibtex/#history

Oh, thanks for the hint! Here the results of my tests.

I'm working on the [`myst-reader`](https://github.com/ashwinvis/myst-reader) project. In my attempt to fix it on Python 3.12, I [updated both `sphinxcontrib-bibtex` and `pybtex`](https://github.com/ashwinvis/myst-reader/pull/30/commits/d04333671796a6a149bdacdc5ead98f09db6d127#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R38-R42) to their unreleased versions:
```toml
sphinxcontrib-bibtex = { git = "https://github.com/mcmtroffaes/sphinxcontrib-bibtex.git", rev = "73afc2329ef4ecc3e4b24fd9ee85461b3336c809" }
pybtex = { git = "https://bitbucket.org/pybtex-devs/pybtex.git", rev = "7066984c8776e3115ae8c78c22c695a184233ef5" }
```

Which [works fine](https://github.com/ashwinvis/myst-reader/pull/30/checks?check_run_id=30042169772).

And I'm happy to confirm that [`sphinxcontrib-bibtex` 2.6.3a4 fix the issue](https://github.com/ashwinvis/myst-reader/pull/30/checks?check_run_id=30042491668) in itself, [without having to specify a dependency on unreleased `pybtex`](https://github.com/ashwinvis/myst-reader/pull/30/commits/24bc42f7ca265b93c2f67acefcaa898e5b7e3917#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L41-R41):
```toml
sphinxcontrib-bibtex = { url = "https://test-files.pythonhosted.org/packages/d2/a0/d4ee08099653bac0e45a8909500ee1cdde099981cebe45e8006c9b256585/sphinxcontrib_bibtex-2.6.3a4-py3-none-any.whl" }
```

So for me it's a go, you can proceed with the release of 2.6.3 on PyPi! 😎

**Comment by mcmtroffaes** [comment]
Swell, thank you so much @kdeldycke for thoroughly testing the relevant combinations of packages - I'll spin a formal release later today.

**Comment by matteosantama** [comment]
I am encountering this problem with Python 3.11. Perhaps `pyproject.toml` could be adjusted

```
 "setuptools; python_version >= '3.12'"  ->  "setuptools; python_version >= '3.11`'" 
```

Python 3.10 doesn't seem to have an issue.

**Comment by matteosantama** [comment]
The problem persists with Python versions 3.9, 3.10, and 3.11. I recommend strengthening the `pyproject.toml` specification from

```
dependencies = [
    ...,
    "setuptools; python_version >= '3.12'"
]
```

to

```
dependencies = [
    ...,
    "setuptools"
]
```

As was previously mentioned,

> Python versions pre 3.12 always installed setuptools into new virtual environments, which is the reason why it mostly worked before.

This is mostly right, but we need to be a little more specific. This change affected the `virtualenv` tool in particular. You can see the change here: https://github.com/pypa/virtualenv/issues/2487. However, there are other ways to create virtual environments too. `venv`, `poetry`, and `rye` to name just a few. 

`poetry` never includes `setuptools` in its virtual environments; this is true regardless of which Python version is being used. See here: https://github.com/python-poetry/poetry/pull/2826. Therefore, we cannot assume `setuptools` is available just because we're using Python < 3.12.

In essence, `sphinxcontrib-biblatex` depends on `pybtex` which depends on `setuptools` (through `pkg_resources`). Nowhere in `pybtex` is `setuptools` listed as a dependency, so it falls on `sphinxcontrib-biblatex` to list it. But this problem is independent of the Python version being used.

**Comment by mcmtroffaes** [comment]
For information, since there's unfortunately no movement on the pybtex front, I've gone ahead and simply declared setuptools as a dependency for all Python versions. This should be part of the next release. Hopefully there will be another release of pybtex at some point so this can be removed again.

**Comment by flying-sheep** [comment]
If pybtex is unmaintained, you could also vendor it (almost no work) or replace it with a maintained alternative (more work initially, but less maintenance work down the road)

**Comment by flying-sheep** [comment]
pybtex still hasn’t made a release, and setuptools now throws a warning that it’ll remove `pkg_resources` this November.

might make sense to think about how to replace it.
