### ISSUE TITLE
Support for @software entries

### ISSUE THREAD

**Issue by maxnoe** [mcmtroffaes/sphinxcontrib-bibtex#347]
I get the following error when running sphinx build:

```
Extension error (sphinxcontrib.bibtex.domain):
Handler <function env_updated at 0x7836ad034220> for event 'env-updated' threw an exception (exception: 'Style' object has no attribute 'format_software')
/home/maxnoe/.local/conda/envs/cta-dev/lib```

**Comment by maxnoe** [comment]
The reason seems to have been that this package currently does not support `@software` entries in bibtex files.

Changing to `@misc` works. However, direct support for @software would be great.

**Comment by mcmtroffaes** [comment]
The pybtex library does the parsing and formatting of bib file entries for sphinxcontrib-bibtex. To support additional entry types, you can create a new style, based on e.g. the pybtex unsrt style, similar to

https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#custom-formatting-sorting-and-labelling

Simply implement a ``get_software_template`` function in the style class to get your desired formatting. You could use the ``@misc`` implementation as a basis:

https://bitbucket.org/pybtex-devs/pybtex/src/2b82780b5090b1c3de0875617b782fbb5b74ba4e/pybtex/style/formatting/unsrt.py#lines-318

I hope this helps!

**Comment by maxnoe** [comment]
Ok, thanks. 

I would be great if the error could be turned into something like:

```
Your current style does not implement the `software` entry type, see <docs page>
```

**Comment by mcmtroffaes** [comment]
I agree it would be nice if pybtex gave a more accurate error message (or even better just fall back on the misc entry type for unknown entry types...).

**Comment by mcmtroffaes** [comment]
I think this can be closed since there's nothing more to do from sphinxcontrib-bibtex's end (it would remain nice if pybtex could give a friendlier error...).

**Comment by partofthething** [comment]
This PR on pybtex should resolve this issue by mapping software directly to misc. https://bitbucket.org/pybtex-devs/pybtex/pull-requests/47

**Comment by Mayitzin** [comment]
Hi, sorry for not opening a new issue, but the error I am getting is quite similar:

```
Extension error (sphinxcontrib.bibtex.domain):
Handler <function env_updated at 0x0000029BB255CB80> for event 'env-updated' threw an exception (exception: open_text is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.)
```

I've checked the suggested site and it simply suggests to substitute all `open_text` with `file` without offering further details.

But I don't really know where that is. I tried a very basic example using `sphinxcontrib-bibtex` (version `2.6.3`) following all the examples. I even got around the `pybtex` dependency issue, but at the moment of the build it throws the error above.

My setup info is:

```
# Platform:         win32; (Windows-10-10.0.19045-SP0)
# Sphinx version:   8.0.2
# Python version:   3.11.2 (CPython)
# Docutils version: 0.21.2
# Jinja2 version:   3.1.4
# Pygments version: 2.18.0
```

Can a samaritan soul help me fix this? At least point me to the right place. I'll take care of the rest.

**Comment by partofthething** [comment]
That's definitely a different issue. The error message starts out the same but has a much different main body:

> exception: open_text is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.

You should make a new one. I recommend also including the version of pybtex in your setup info.

FWIW I'm not seeing that particular error on `sphinxcontrib-bibtex==2.6.3`
