### ISSUE TITLE
Hyperlink from {cite} to bibliography across documents?

### ISSUE THREAD

**Issue by gradill22** [mcmtroffaes/sphinxcontrib-bibtex#348]
I have multiple documents in my Jupyter Book project that cites dozens of sources. I want a bibliography page that is its own document while referencing the citations I've made in previous documents with backlinks? Is this possible with sphinx? Or is it too much to ask from it so far?

**Comment by mcmtroffaes** [comment]
I don't know how Jupyter works exactly, but sphinx supports your scenario out of the box, even without this extension. The main thing this extension adds is importing the citations themselves from a bib file. Good luck!

**Comment by gradill22** [comment]
Will it still be able to do this with backlinks to where sources were cited?

To be clear, I want hyperlinks from the bibliography page to where a source was cited, kind of like a footnote bibliography. Is this still possible with a standard bibliography that holds citations across multiple documents? I have no trouble going from cited sources to its place in the bibliography. Perhaps I was unclear the first time.

**Comment by mcmtroffaes** [comment]
As said, yes, sphinx does this out of the box with all citations.
