### ISSUE TITLE
setup.py: migrate deprecated namespace_packages

### ISSUE THREAD

**Issue by danielnorberg** [mcmtroffaes/sphinxcontrib-bibtex#350]
Please consider changing to native namespace packages.

https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages

**Comment by mcmtroffaes** [comment]
This was changed a long time ago:

https://github.com/mcmtroffaes/sphinxcontrib-bibtex/commit/65153f78ae9c7248dc31de6597acf062f6c11aab

If you still see an ``__init__.py``, it must be from another package.

**Comment by danielnorberg** [comment]
Installing `sphinxcontrib_bibtex` `2.6.2` still seems to cause a namespace package pth to be created in `site-packages`:

```
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install sphinxcontrib-bibtex
... 
Successfully installed ... sphinxcontrib-bibtex-2.6.2 ...

$ ll venv/lib/python3.10/site-packages/sphinxcontrib_bibtex-2.6.2-py3.12-nspkg.pth
-rw-r--r-- 1 root root 574 Sep  6 12:38 venv/lib/python3.10/site-packages/sphinxcontrib_bibtex-2.6.2-py3.12-nspkg.pth
```

Might this be because `setup.py` [still specifies](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/3dc7c2e81999c35c9e722deb28b2aeed62c2187f/setup.py#L70) `namespace_packages=["sphinxcontrib"]`? 

https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
https://setuptools.pypa.io/en/latest/history.html#id436

**Comment by danielnorberg** [comment]
Building this package I indeed get a deprecation warning for `namespace_packages`.

```
$ git clone git@github.com:mcmtroffaes/sphinxcontrib-bibtex.git
$ cd sphinxcontrib-bibtex
$ python setup.py build
/home/dano/src/sphinxcontrib-bibtex/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
/home/dano/src/sphinxcontrib-bibtex/venv/lib/python3.8/site-packages/setuptools/dist.py:655: SetuptoolsDeprecationWarning: The namespace_packages parameter is deprecated.
!!

        ********************************************************************************
        Please replace its usage with implicit namespaces (PEP 420).

        See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages for details.
        ********************************************************************************

!!
  ep.load()(self, ep.name, value)
```

**Comment by mcmtroffaes** [comment]
Thanks for the logs. Indeed, I agree, it looks like a setup.py needs a corresponding change. I've update the description accordingly.
