### ISSUE TITLE
"open_text is deprecated" error

### ISSUE THREAD

**Issue by mcmtroffaes** [mcmtroffaes/sphinxcontrib-bibtex#352]
_Originally posted by @Mayitzin in https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/347#issuecomment-2367079731_

Hi, sorry for not opening a new issue, but the error I am getting is quite similar:

```
Extension error (sphinxcontrib.bibtex.domain):
Handler <function env_updated at 0x0000029BB255CB80> for event 'env-updated' threw an exception (exception: open_text is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.)
```

I've checked the suggested site and it simply suggests to substitute all `open_text` with `file` without offering further details.

But I don't really know where that is. I tried a very basic example using `sphinxcontrib-bibtex` (version `2.6.3`) following all the examples. I even got around the `pybtex` dependency issue, but at the moment of the build it throws the error above.

My setup info is:

```
# Platform:         win32; (Windows-10-10.0.19045-SP0)
# Sphinx version:   8.0.2
# Python version:   3.11.2 (CPython)
# Docutils version: 0.21.2
# Jinja2 version:   3.1.4
# Pygments version: 2.18.0
```

Can a samaritan soul help me fix this? At least point me to the right place. I'll take care of the rest.

**Comment by mcmtroffaes** [comment]
Thanks for reporting @mayitzin - sadly I cannot reproduce... Can you run pip freeze to check your package versions?

**Comment by Mayitzin** [comment]
Hi, sure, here it is:

```
accessible-pygments==0.0.5
-e git+https://github.com/Mayitzin/ahrs.git@c2ffe02791d7e7bd83dc5950ff850b5640c371e9#egg=AHRS
alabaster==1.0.0
babel==2.16.0
beautifulsoup4==4.12.3
certifi==2024.8.30
charset-normalizer==3.3.2
colorama==0.4.6
docutils==0.21.2
idna==3.10
imagesize==1.4.1
Jinja2==3.1.4
latexcodec==3.0.0
MarkupSafe==2.1.5
numpy==2.0.0
packaging==24.1
-e git+https://bitbucket.org/pybtex-devs/pybtex.git@7066984c8776e3115ae8c78c22c695a184233ef5#egg=pybtex
pybtex-docutils==1.0.3
pydata-sphinx-theme==0.15.4
Pygments==2.18.0
PyYAML==6.0.2
readthedocs-sphinx-ext==2.2.5
requests==2.32.3
six==1.16.0
snowballstemmer==2.2.0
soupsieve==2.6
Sphinx==8.0.2
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-bibtex==2.6.3
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
typing_extensions==4.12.2
urllib3==2.2.3
```

Adding more context:

Yesterday I installed `sphinxcontrib-bibtex` using `pip`, and initially ran into the compatibility problem raised by pybtex as explained in the [other issue](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/345).

The maintainer of pybtex did update the package, but not to pypi. So, I cloned the repository from bitbucket, and installed it locally. It fixed the problem.

I build the documentation using the created `Makefile` during the setup of the Sphinx documentation. The call `make html` runs everything already.

However, now the problem shows up with the following output:

```
Running Sphinx v8.0.2
loading translations [en]... done
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
checking bibtex cache... out of date
parsing bibtex file C:\ahrs\docs\source\refs.bib... parsed 1 entries
building [mo]: targets for 0 po files that are out of date
writing output...
building [html]: targets for 109 source files that are out of date
updating environment: [new config] 109 added, 0 changed, 0 removed
reading sources... [100%] world_models

Extension error (sphinxcontrib.bibtex.domain):
Handler <function env_updated at 0x0000025DC257CB80> for event 'env-updated' threw an exception (exception: open_text is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.)
```

The file `refs.bib` has a single entry for an article, and the file is in the same directory as the `conf.py` file.

The `conf.py` has updated only the values to use `sphinxcontrib-bibtex`, as in the examples at the website.

From here, I don't know what else can it be updated, modified, as I think I already have the latest versions for each package.

Thanks for your reply and for your kind assistance.

Mario.

**Comment by mcmtroffaes** [comment]
Thanks for the pip output. It looks ok...

On thing that occurs to me: no workaround should be needed with the latest sphinxcontrib-bibtex. Can you try uninstalling pybtex and installing it from pypi instead of from git? I suspect you'll still get the same error but it'd be good to eliminate it as a cause.

If it isn't fixed this way, I wonder if you could get a full traceback for the error, maybe from the logs? I ask because sphinxcontrib-bibtex [does not use the "open_text" function anywhere](https://github.com/search?q=repo%3Amcmtroffaes%2Fsphinxcontrib-bibtex%20open_text&type=code). If it did it would be an easy fix. So... we need to know where this function is called to know how to fix it.

**Comment by Mayitzin** [comment]
Hi, I re-installed pybtex from the pypi, and now we get the previous error:

```
Running Sphinx v8.0.2
loading translations [en]... done

Exception occurred:
  File "C:\ahrs\env\Lib\site-packages\pkg_resources\__init__.py", line 103, in <module>
    warnings.warn(
DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
The full traceback has been saved in C:\Users\Mayitzin\AppData\Local\Temp\sphinx-err-mini52pn.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

The logged traceback shows us the culprit. As expected it lies in the deprecated imports of `pybtex`.

```
# Platform:         win32; (Windows-10-10.0.19045-SP0)
# Sphinx version:   8.0.2
# Python version:   3.11.2 (CPython)
# Docutils version: 0.21.2
# Jinja2 version:   3.1.4
# Pygments version: 2.18.0

# Last messages:


# Loaded extensions:


# Traceback:
Traceback (most recent call last):
  File "C:\ahrs\env\Lib\site-packages\sphinx\cmd\build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ahrs\env\Lib\site-packages\sphinx\application.py", line 253, in __init__
    self.setup_extension(extension)
  File "C:\ahrs\env\Lib\site-packages\sphinx\application.py", line 429, in setup_extension
    self.registry.load_extension(self, extname)
  File "C:\ahrs\env\Lib\site-packages\sphinx\registry.py", line 448, in load_extension
    mod = import_module(extname)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ahrs\env\Lib\site-packages\sphinxcontrib\bibtex\__init__.py", line 14, in <module>
    from .directives import BibliographyDirective
  File "C:\ahrs\env\Lib\site-packages\sphinxcontrib\bibtex\directives.py", line 21, in <module>
    from .bibfile import _make_ids, normpath_filename
  File "C:\ahrs\env\Lib\site-packages\sphinxcontrib\bibtex\bibfile.py", line 23, in <module>
    from pybtex.database import BibliographyData, BibliographyDataError
  File "C:\ahrs\env\Lib\site-packages\pybtex\database\__init__.py", line 44, in <module>
    from pybtex.plugin import find_plugin
  File "C:\ahrs\env\Lib\site-packages\pybtex\plugin\__init__.py", line 26, in <module>
    import pkg_resources
  File "C:\ahrs\env\Lib\site-packages\pkg_resources\__init__.py", line 103, in <module>
    warnings.warn(
DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
```

As you mentioned, `sphinxcontrib-bibtex` should have dealt with it in the newest release (https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/345), but it apparently isn't for me.

- Could it be that I'm still using Python 3.11?
- Should I re-install `sphinxcontrib-bibtex`, but using the wheels of the GitHub release? (https://github.com/mcmtroffaes/sphinxcontrib-bibtex/releases/tag/2.6.3)
- Maybe clone the repository and install it like `pybtex`?

I will try different configurations and try to figure out what is going on.

**Comment by mcmtroffaes** [comment]
Thanks for testing. I didn't realize pkg_resources gave a depreciation warning; #345 fixed the import error but not the depreciation... Without a pybtex release on pypi unfortunately we're stuck. I guess I may have to fork the project to keep the extension supported.

I'd say right now the most useful information for your issue would be to get a traceback for the "open_text" warning, with pybtex from git.

**Comment by mcmtroffaes** [comment]
... oh, another thing: DeprecationWarnings shouldn't normally raise exceptions. Do you have these configured to raise? See https://docs.python.org/3/library/warnings.html#describing-warning-filters

**Comment by partofthething** [comment]
> ... oh, another thing: DeprecationWarnings shouldn't normally raise exceptions. Do you have these configured to raise? See https://docs.python.org/3/library/warnings.html#describing-warning-filters

this _has_ to be the issue. @Mayitzin, do you have any code like this in your project? If so, removing that will allow deprecation warnings to just be printed without stopping execution (typically the intent)

```python
import warnings
warnings.filterwarnings("error")
```

**Comment by mcmtroffaes** [comment]
Thanks @partofthething That's very helpful!

**Comment by Mayitzin** [comment]
THAT was the issue! Sorry, I had time just now to test it. I grepped my directory and found an old file using those lines precisely.

Now I can build beautiful bibliographic pages. Thanks again @mcmtroffaes for the package and support, and @partofthething for the input.

You can close this as solved.
