### ISSUE TITLE
LaTeX output generates an extra "References" title whilst html output does not

### ISSUE THREAD

**Issue by mcmtroffaes** [mcmtroffaes/sphinxcontrib-bibtex#48]
Reported on stackoverflow: http://stackoverflow.com/questions/16776628/sphinxcontrib-bibtex-problems-when-making-latexpdf-document

To fix discrepancies between html and latex output, we need to fix the latex writer to use the bibtopic package instead (not sure if upstream would accept this... we can sure try).

**Comment by cpitclaudel** [comment]
Any updates on this?

**Comment by cpitclaudel** [comment]
Is there an open issue upstream? I couldn't find one.

**Comment by mcmtroffaes** [comment]
I haven't found one either.

**Comment by xuhdev** [comment]
Can we just add a reference title to the HTML output? Or, to suppress the title in LaTeX output, refer to https://tex.stackexchange.com/a/132647/29103

**Comment by xuhdev** [comment]
@mcmtroffaes Thanks for the modification. Actually what I meant is that it is a bit disturbing that by default one of the workaround is required. Why not make the title always visible by default, and users can choose to turn it off (or the other way around)?

**Comment by mcmtroffaes** [comment]
I agree, but it's an upstream problem: the issue happens whether or not the sphinxcontrib-bibtex extension is used.

**Comment by xuhdev** [comment]
What is the upstream issue? Is it that LaTeX always generating a Reference title? I don't think this is a "problem", because LaTeX is supposed to generate a title automatically for the users, because the title (Reference, Bibliography, or whatever) is something that is determined by the style file and that varies across different publishers and journals. It's not what a user should need to take care of by default. However, in our context, IMHO, we should make things consistent across HTML and LaTeX output.

**Comment by fcarvalhopacheco** [comment]
Hi @mcmtroffaes and all, thanks for this discussion! 

I am still getting two `Bibliography` titles on my `Table of contents`. Please [see the full pdf here](https://whots-annual-report.readthedocs.io/_/downloads/whots16-data-report/en/latest/pdf/). I tried many things include [Mismatch Between Output of HTML/Text and LaTeX Backends](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#mismatch-between-output-of-html-text-and-latex-backends).

My `index.md` is [here](https://github.com/hot-dogs/whots16-data-report/blob/main/docs/source/index.md)
My `references.md` is [here](https://github.com/hot-dogs/whots16-data-report/blob/main/docs/source/references.md). 
- You probably noticed i am using markdown (myst-parser) for this project. But I still tried to follow your conversation by doing 
````
```{eval-rst}
.. raw:: latex

   \cleardoublepage
   \begingroup
   \renewcommand\chapter[1]{\endgroup}
   \phantomsection

.. _refs:

References
==========

.. bibliography::
```
````

My `conf.py` is [here](https://github.com/hot-dogs/whots16-data-report/blob/main/docs/source/conf.py)
- You will notice that my [`preamble`](https://github.com/hot-dogs/whots16-data-report/blob/f081c79ecaf460b050f12d3c9506cdf0b6e0efa4/docs/source/conf.py#L121)  calls [`mystyle.sty`](https://github.com/hot-dogs/whots16-data-report/blob/f081c79ecaf460b050f12d3c9506cdf0b6e0efa4/docs/source/latex_templates/mystyle.sty) file.



Any thoughts would be much appreciated!
