### ISSUE TITLE
Handling patent entries

### ISSUE THREAD

**Issue by moorepants** [mcmtroffaes/sphinxcontrib-bibtex#5]
I have some @patents in my bib database. I get this exception from pybtex:

``` pytb
File "/usr/local/lib/python2.7/dist-packages/pybtex/style/formatting/__init__.py", line 56, in format_entries
    f = getattr(self, "format_" + entry.type)
AttributeError: 'Style' object has no attribute 'format_patent'
```

Looks like the pybtex.style.formatting.unsrt.Style class doesn't handle that for some reason.

I can post this to pybtex instead, but I saw that you've been pushing to pybtex too.

**Comment by partofthething** [comment]
Just for the record: here's the relevant issue in pybtex: https://bitbucket.org/pybtex-devs/pybtex/issues/157/support-for-software-and-patent-entries-in

Zotero creates patent types by default when you click its extension in a google patent page so that's probably driving interest in this.
