### ISSUE TITLE
Support for text commands of biblatex?

### ISSUE THREAD

**Issue by bk322** [mcmtroffaes/sphinxcontrib-bibtex#71]
In biblatex

``` latex
\citeauthor{KEY}  % uses author, editor, or translator fields
\citeauthor*{KEY} % force maxcitenames to 1, and adds et al

\citetitle{KEY}   % uses shorttitle if available
\citetitle*{KEY}  % uses title

\citeyear{KEY}    % year field or year component of date
\citeyear*{KEY}   % includes the extrayear information, if any

\citeurl{KEY}
```

It might be possible to add at least simplest of these to the package. For example `:citeauthor:` for `\citeauthor`.

**Comment by mcmtroffaes** [comment]
I've just merged #230 so inline citations are now fully customizable in develop, whence this is basically done. There are basic ``:cite:author:`` (just gets the author but could be updated to also look at the editor/translator if need be, standard natbib doesn't do this so I've left it out for now) and ``:cite:year:`` roles, no ``:cite:title:`` yet but that should be easy to add.
