### ISSUE TITLE
citations not always found

### ISSUE THREAD

**Issue by mcmtroffaes** [mcmtroffaes/sphinxcontrib-bibtex#8]
(forked from issue #2)

When a citation occurs in a file that is parsed before the file with the corresponding bibliography directive is parsed, that citation will not be resolved. A temporary workaround for this problem is to ensure that your bibliography resides in a file that is alphabetically last.

Implementation note: the cause of this problem is that docutils/sphinx applies its transforms immediately after initial parsing of each doctree, instead of waiting until all initial doctrees are constructed?

**Comment by mickours** [comment]
Hi,

I don't know if it is the same issue but I get a citation not found warning for a specific entry that is present in the bibtex file.

The citation in the rst file:
```
:cite:`felter_updated_2014`
```

The sphinx-build output in verbose and there is no other warnings about the bibtex parsing:
```
[app] emitting event: 'missing-reference'(<sphinx.environment.BuildEnvironment object at 0x7f87b59b9320>, <pending_xref: <#text: '[felter_upd
...
None:14: WARNING: citation not found: felter_updated_2014
```

The bibtex entry is:
```
@article{felter_updated_2014,
	title = {An updated performance comparison of virtual machines and linux containers},
	volume = {28},
	url = {http://www.cs.nyu.edu/courses/fall14/CSCI-GA.3033-010/vmVcontainers.pdf},
	urldate = {2016-01-13},
	journal = {technology},
	author = {Felter, Wes and Ferreira, Alexandre and Rajamony, Ram and Rubio, Juan},
	year = {2014},
	pages = {32},
	file = {[PDF] à partir de nyu.edu:/home/mercierm/.zotero/zotero/ntgs4det.default/zotero/storage/VJGZMTT4/Felter et al. - 2014 - An updated performance comparison of virtual machi.pdf:application/pdf}
}
```

I precise that all the others references in the same file are rendered correctly.

Any idea?

**Comment by mcmtroffaes** [comment]
Is your bibliography in a separate file that comes alphabetically last? If not, that should be the first thing to fix. If it is, maybe you ran into a bug. Do you have a minimal test case for reproducing the problem?

**Comment by mickours** [comment]
Sorry I had misunderstand the workaroud and I moved the actual ``.bib`` bibliography file and not the ``.rst`` file that contains the rendered bibliography.

It works now thanks!

**Comment by dabail10** [comment]
I am having this trouble again. The output follows. I have a separate file preferences.rst as suggested early, and the reference list is being generated correctly. However, the in text citation links are not working.

Dave
Boulder, CO

Running Sphinx v1.5.3
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/2/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 14 source files that are out of date
updating environment: 14 added, 0 changed, 0 removed
checking for /Users/dbailey/CICE/doc/source/users_guide/master_list.bib in bibtex cache... not found                                
parsing bibtex file /Users/dbailey/CICE/doc/source/users_guide/master_list.bib... parsed 50 entries

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] users_guide/zreferences                                                                                    
/Users/dbailey/CICE/doc/source/users_guide/ice_nml_example.rst:22: WARNING: citation not found: cice15
/Users/dbailey/CICE/doc/source/users_guide/ice_nml_var.rst:28: WARNING: citation not found: cice15
/Users/dbailey/CICE/doc/source/users_guide/ice_what_is_cice5.rst:7: WARNING: citation not found: cice15
/Users/dbailey/CICE/doc/source/users_guide/ice_what_is_cice5.rst:19: WARNING: citation not found: cice15
/Users/dbailey/CICE/doc/source/users_guide/ice_what_is_cice5.rst:41: WARNING: citation not found: cice15
/Users/dbailey/CICE/doc/source/users_guide/ice_what_is_cice5.rst:41: WARNING: citation not found: turner15
/Users/dbailey/CICE/doc/source/users_guide/ice_what_is_cice5.rst:41: WARNING: citation not found: cice15
/Users/dbailey/CICE/doc/source/users_guide/ice_what_is_cice5.rst:66: WARNING: citation not found: turner15
/Users/dbailey/CICE/doc/source/users_guide/ice_what_is_cice5.rst:68: WARNING: citation not found: hunke13
/Users/dbailey/CICE/doc/source/users_guide/ice_what_is_cice5.rst:74: WARNING: citation not found: assur58
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 10 warnings.

**Comment by dabail10** [comment]
Update. I figured out some of the issue. When I do the following:

.. rubric:: References

.. bibliography:: master_list.bib
   :cited:
   :list: enumerated

It breaks the citations. When I removed the :list: directive it works again!

Dave

**Comment by mcmtroffaes** [comment]
Glad you got this resolved!

I checked the documentation for this, and the behaviour you encountered is indeed documented: https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#bullet-lists-and-enumerated-lists in particular: "Note that citations to these types of bibliography lists will not be resolved."

**Comment by dabail10** [comment]
I missed that the first time around. This would be a nice feature though. Any plans to add enumerated citation labels?

Dave

**Comment by mcmtroffaes** [comment]
The problem is that enumerated lists per definition don't have unique labels, so if you like to have those, it doesn't make sense to use them. If you want numbered labels, I'd suggest to use the plain style from bibtex. That will be much like an enumerated list but with proper labels, backlinks, etc. Ok?

**Comment by dabail10** [comment]
Thanks. I will look into this. This is such a good package and our documentation is coming together quite nicely. In case you are curious, the HTML is here:

https://ncar.github.io/CICE/doc/build/html/users_guide/index.html

**Comment by mcmtroffaes** [comment]
Nice, thanks for sharing that!

**Comment by 1kastner** [comment]
> The problem is that enumerated lists per definition don't have unique labels, so if you like to have those, it doesn't make sense to use them. If you want numbered labels, I'd suggest to use the plain style from bibtex. That will be much like an enumerated list but with proper labels, backlinks, etc. Ok?

As a workaroud, I defined my custom CSS (just included to my sphinx documentation the default way):

```CSS
dl.citation dt.label {
    display: none !important;
}

dl.citation dd {
    display: list-item;
    list-style-type: arabic;
}
```

Thus, I can have an enumerated list of my sources and avoid the labels being displayed. I hope this helps somebody.
