### ISSUE TITLE
:cite: in replace directive

### ISSUE THREAD

**Issue by pinsardfr** [mcmtroffaes/sphinxcontrib-bibtex#84]
Hi,

It seems that :cite: can not be used in a replace directive

Here what I wrote in my rst file (to bypass limited bibstyle)  

    .. |DCM214_pagobibstyle| replace:: Deshayes et al., 2014 :cite:`deshayes:hal-01128173`

    |DCM214_pagobibstyle|

While 
    :cite:`deshayes:hal-01128173`

give the expected result ie `[1]` linking to the zreferences.html, I have an error message from Sphinx 1.3.1 

    ERROR: Substitution definition contains illegal element:

    <citation_reference ids="id2" refname="deshayes:hal-01128173">
    deshayes:hal-01128173

    .. |DCM214_pagobibstyle| replace:: Deshayes et al., 2014 :cite:`deshayes:hal-01128173`
    /Users/fplod/pago_ws/docs/manual/source/overview.rst:56: ERROR: Undefined substitution referenced: "DCM214_pagobibstyle".

I am using sphinxcontrib-bibtex 0.3.2.

Regards

**Comment by mcmtroffaes** [comment]
Apparently docutils doesn't support citations in replace directives:

``` {.rest}
Citation references, like [CIT2002]_.
Another one |CIT2002_STYLE|.

.. [CIT2002] Author. 2002.

.. |CIT2002_STYLE| replace:: Author, 2002 [CIT2002]
```

The reference in the second sentence won't be converted properly (tested with docutil's rst2html, version 0.12). If this gets fixed by upstream docutils, then your sphinxcontrib-bibtex example should work as well.

**Comment by pinsardfr** [comment]
thanks

I submit issue http://sourceforge.net/p/docutils/mailman/message/34367956/ to docutils-users list.

**Comment by mcmtroffaes** [comment]
Thanks for reporting this upstream!
