### ISSUE TITLE
Support docstring local bibliographies

### ISSUE THREAD

**Issue by marscher** [mcmtroffaes/sphinxcontrib-bibtex#87]
How difficult would this be to implement. I think you already mentioned something about this in #52. It would be really nice to have this feature, since a method/function could in principle refer to some articles. 
The current behaviour is to hyperlink the citation in the same document in which bibliography it has been cited first. This way your browser will jump from the current docstring to a method/function, where this has been cited first, which is somehow confusing.

Maybe this is already supported or literally impossible due to some sphinx specific design issues? Sorry I'm fairly new to this extension...
Thank you very much!

**Comment by mcmtroffaes** [comment]
Well, you could simply have per-document bib files and duplicate the entries but with different labels, as suggested here:

https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/52#issuecomment-38897035

I agree it's a "hacky" solution.

Better would be to have simple per-document bibliographies. This would also solve a whole bunch of other problems, like unresolved citations across documents, and it would enable parallel builds.

**Comment by marscher** [comment]
I'd not prefer hacky solutions, since I just estimated the effort of 
switching from "plain" references to bibtex.

But it sounds like implementing this would gain a lot of improvements :+1:

**Comment by mcmtroffaes** [comment]
Yes. The way to go, as I think of it now, is to have a special flag in the config file which forces all bibliographies to be local to the file they are defined in. Obviously still different labels across documents are needed (for example using different prefixes per document), but I believe that's workable.

**Comment by mcmtroffaes** [comment]
... well maybe it would be simpler to attach a special tag to each bibliography, and to each citation, so the bibliography only grows entries for citations that match the tag. This gives the most flexibility i.e. it allows the user to fully control the scope. It also then allows global & local bibliographies to coexist in totally separate manners, and removes issues with duplicate references (but not with duplicate labels - you still have to deal with this by prefixing or some other method).

**Comment by mcmtroffaes** [comment]
Here's the idea.

In refs.bib:

```
@article{wald1939, ...}
```

In doc1.rst:

```
:cite:`local1-wald1939`

... bibliography: refs.bib
    :tag: local1
    :prefix: A
```

In doc2.rst, or really anywhere (could even be again in doc1.rst!!):

```
:cite:`local2-wald1939`

... bibliography: refs.bib
    :tag: local2
    :prefix: B
```

The prefix makes sure that no duplicate labels occur (this is only necessary if you know that you will be referring to the same document in multiple places). There's no way around that: sphinx always treats citations as global no matter what.

Does this seem sensible from a user perspective?

**Comment by marscher** [comment]
Am 20.10.2015 um 09:48 schrieb Matthias C. M. Troffaes:
> Here's the idea.
>
> In refs.bib:
>
> |@article{wald1939, ...} |
>
> In doc1.rst:
>
> |:cite:`local1-wald1939` ... bibliography: refs.bib :tag: local1 :prefix: A |
>
> In doc2.rst, or really anywhere (could even be again in doc1.rst!!):
>
> |:cite:`local2-wald1939` ... bibliography: refs.bib :tag: local2 :prefix: B |
>
> The prefix makes sure that no duplicate labels occur (this is only
> necessary if you know that you will be referring to the same document in
> multiple places). There's no way around that: sphinx always treats
> citations as global no matter what.
Then this is a good workaround.
>
> Does this seem sensible from a user perspective?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/87#issuecomment-149465942>.
>
This approach seems to be very practical and offers a lot of flexibility.

**Comment by mcmtroffaes** [comment]
Well, this was amazingly easy to implement. Could you give the https://github.com/mcmtroffaes/sphinxcontrib-bibtex/tree/feature/bibliography-tags branch a quick spin with the new keyprefix option to see if it works for your use case? Also if you could have a look at the documentation to see if it is clear enough, that would be appreciated: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/feature/bibliography-tags/doc/usage.rst#key-prefixing-for-local-bibliographies

**Comment by marscher** [comment]
Thank you very much for the quick solution. 

I've tried adding different keys and labels for the two functions sharing the same bib file, but the citations are not being found, if the keys/labels are present.

```
None:102: WARNING: citation not found: swope_describing_2004
None:81: WARNING: citation not found: swope_describing_2004
```

The bib file contains more entries. I've used different label and key prefixes in two functions (defined in the same file). Every function cites in this example the entry "swope_describing_2004", but as stated they entry is not being found.

If I omit the key/label prefixes, the keys are found but of course referenced only in one of the both bibliographies.

**Comment by mcmtroffaes** [comment]
Thanks for the quick reply. Can you share your code for me to test what's possibly going wrong?

**Comment by marscher** [comment]
It is public, but has unfortunately a lot of dependencies. Should I try 
to extract a minimum (failing) example?

Anyway the code can viewed here:

https://github.com/marscher/PyEMMA/tree/sphinx_bibtex

The file, where I've added the prefixes is here:
https://github.com/marscher/PyEMMA/commit/80bd4b3dbbcdbe96de5f0e302d1f881b382569e4

**Comment by mcmtroffaes** [comment]
I've commented on what I think is the problem. Let me know how you fare if you fix the citation keys with their proper prefixes.

**Comment by marscher** [comment]
Sorry, where did you comment on that?

**Comment by mcmtroffaes** [comment]
https://github.com/marscher/PyEMMA/commit/80bd4b3dbbcdbe96de5f0e302d1f881b382569e4#commitcomment-13875386

**Comment by marscher** [comment]
Never mind. Now it works like a charm.

**Comment by marscher** [comment]
Just one comment on the key prefix. Is it necessary to show this prefix in the html output? I thought it is just a technical thing to generate unique keys.
With style: plain I'd expect to have "plain" numbers for citations.

**Comment by mcmtroffaes** [comment]
I guess you could simply try omitting the labelprefix option. I've forgotten what exactly happens if you do this, but sphinx definitely complains about duplicate labels. The problem with duplicate labels was originally discussed here: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/14 Apparently the html result looks a bit weird if you allow duplicate labels; any improvement in that direction would have to be patched against sphinx itself rather than against this extension.

Anyway, the core of the local bibliography problem is solved, so I'll close this issue. If you have any other thoughts for improvements, please do send them this way.

**Comment by marscher** [comment]
Thank you very much!
