### ISSUE TITLE
Local bibliography KeyPrefix: duplicated citation in the latexpdf output

### ISSUE THREAD

**Issue by xuhdev** [mcmtroffaes/sphinxcontrib-bibtex#90]
While the option `:keyprefix:` solves the problem for HTML output of local bibliography, the pdf output still generates duplicated reference entries. Is there any way to fix this? Thanks!

**Comment by mcmtroffaes** [comment]
How are you generating pdf? Via latex?

If so then, well, Sphinx's latex writer doesn't attempt to mimick the html citation system and instead assumes a single bibliography. This has nothing to do with the sphinxcontrib-bibtex extension, it's just the way Sphinx works at the moment. So yes it will simply appear to duplicate entries. Also see here in the documentation:

https://sphinxcontrib-bibtex.readthedocs.org/en/latest/usage.html#mismatch-between-output-of-html-and-latex-backends

If you need to write pdf via latex, then at the moment you can't use local bibliographies, until upstream decides to properly support this scenario. Issue #48 is tracking progress on this but so far I haven't had much time to work on it as it would pretty much amount to a rewrite of a large part of Sphinx's latex writer - but by all means give it a go if you want.

You could also try to generate pdf via rst2pdf which bypasses latex completely, however unfortunately this extension seems to be broken (I just tested it again to see if there was any change, sadly not).

I'm very sorry that I can't be more helpful at this moment.

**Comment by mcmtroffaes** [comment]
... ah yes via latexpdf (didn't see it in the title originally!)
