### ISSUE TITLE
specify global options

### ISSUE THREAD

**Issue by xuhdev** [mcmtroffaes/sphinxcontrib-bibtex#91]
Every time I want to use bibliography, I have to type:

    .. bibliography:: refs.bib
        :style: unsrt

Is there any way to specify this global style in `conf.py`? Thanks!

**Comment by mcmtroffaes** [comment]
Not at the moment, but it's easy to implement - I'll look into adding it as I agree this would be pretty useful.

**Comment by karlnapf** [comment]
Would love to have this as well

**Comment by mcmtroffaes** [comment]
Sorry this took so long - this is now supported in the develop branch and will be included in the next release.

**Comment by xuhdev** [comment]
Thank you!
