### ISSUE TITLE
`:cite:` inside a figure caption fails the latexpdf output

### ISSUE THREAD

**Issue by xuhdev** [mcmtroffaes/sphinxcontrib-bibtex#92]
When `:cite:` is used inside a figure caption, the following error message shows for the latexpdf output:

    Incomplete \iffalse; ; all text was ignored after line xxx

I figured out the reason---`\phantomsection` cannot be used in a caption. Once I removed phantomsection, the compilation passed. Is there any reason we use phantomsection here?

**Comment by mcmtroffaes** [comment]
It sounds like you've hit a bug in sphinx's latex writer not being able to handle citations in figure captions. The extension itself is not concerned with any specific backends and simply generates reference nodes (as standard rest citations would).

Anyway, my guess is that sphinx uses phantomsection to permit back-references. If latex doesn't support these inside captions and you really rely on this, then I suggest that you override the writer with one that doesn't support hypertargets; from a quick scan of the sphinx source code, you just need to override the LaTeXTranslator.hypertarget function to return an empty string:

https://github.com/sphinx-doc/sphinx/blob/17e38457049ddbf3e069cd033b119db0e80addca/sphinx/writers/latex.py#L332

Another solution is of course not to have references (or any other hypertargets) inside captions.

Does this help?

**Comment by xuhdev** [comment]
@mcmtroffaes Thanks for your reply. I've found another solution is to add the following to the LaTeX preamble:

```latex
\usepackage{etoolbox}
\AtBeginEnvironment{figure}{\renewcommand{\phantomsection}{}}
```

Would you mind me making a PR to add a note to the documentation?

**Comment by mcmtroffaes** [comment]
Not at all - bring it on! I agree this is a better workaround; thanks in advance.

**Comment by xuhdev** [comment]
I just found sphinx-doc/sphinx#2134, which I believe is the same issue but was fixed just one day we added the notes.

**Comment by mcmtroffaes** [comment]
Hah, great! :-)
