### ISSUE TITLE
The sphinxcontrib.bibtex extension is not safe for parallel reading

### ISSUE THREAD

**Issue by RobertoBagnara** [mcmtroffaes/sphinxcontrib-bibtex#96]
Can it be made safe?

**Comment by mcmtroffaes** [comment]
In general it is not safe. See https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/80 for more details behind this.

**Comment by andreacassioli** [comment]
Sorry to jump in. 

I am still wondering at this issue. What is exactly the reason for which sphinxcontrib.bibtex cannot be made parallel read safe? Still not clear to me even after #80...

**Comment by mcmtroffaes** [comment]
In the current design, the bibliography directive must be processed after citations because otherwise there's no way to know which entries to include in the bibliography...

**Comment by mcmtroffaes** [comment]
Just to note that this is now being worked on, see #210.
