### ISSUE TITLE
hyperlink from :cite: to citation in HTML?

### ISSUE THREAD

**Issue by newville** [mcmtroffaes/sphinxcontrib-bibtex#98]
I'm trying to use sphinxcontrib-bibtex to replace natbib, so apologies if this is not an Issue.  I'm using sphinxcontrib-bibtex from the current github master and sphinx 1.3.1.

I'd like to have the citation give a cross-reference and hyperlink to the bibliography entry in the HTML version documentation.  the natbib package I was surprised this doesn't happen -- could I be doing something wrong?    The bibliography file is being parsed and displayed correctly (and, very nicely, BTW!), and the citation is displayed in the place of the `:cite:` directive, but it is not a hyperlink.

I don't actually see such a cross-reference in any of the examples.   If this is not already implemented, and I'm simply doing something silly, would this be a desirable feature for sphinxcontrib-bibtex?

**Comment by mcmtroffaes** [comment]
Sorry for not getting back to you earlier. Cross references should work both ways as is... Do you have a minimal test case showing the problem?

**Comment by newville** [comment]
@mcmtroffaes   A minimal example, including `conf.py` is at 
    https://gist.github.com/newville/13e0c6d7179ce752422e70638cdc4c3b

I *think* I'm following the docs correctly, with `index.rst` of:

```rst
   See the work of :cite:`Author2016` for more information.

.. rubric:: References

.. bibliography:: refs.bib
   :list: enumerated
   :style: unsrt
```

Doing 
```sh

sphinx-build -b html -d _build/doctrees -D latex_paper_size=letter  . _build/html
sphinx-build -b html -d _build/doctrees -D latex_paper_size=letter  . _build/html
```

generates the bibliography correctly from the bibtex file, but the html text is

```html
<p>See the work of [Author2016] for more information.</p>
<p class="rubric">References</p>
<ol class="arabic simple" id="bibtex-bibliography-index-0" start="1">
<li>A.&nbsp;B. Author and X.&nbsp;Y. Another. Really neat findings. <em>Journal of Choice</em>, 6(1):121–128, 2016.</li>
</ol>
```

That is, without a hyperlink from the citation to the bibliography entry.

I'm using sphinx 1.3.1.

**Comment by mcmtroffaes** [comment]
At first sight your source looks ok and yes sphinx should generate cross-references, not sure why it doesn't work. In addition, the generated label is wrong - with style unsrt it should generate numeric labels rather than alphanumeric ones. I'll need to investigate this in more detail.

**Comment by mcmtroffaes** [comment]
I looked at your code in detail now - if you use an enumerated style, then the extension won't produce links and backlinks. Use the default style instead (which will generate proper docutils citations). This is documented here:

https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#bullet-lists-and-enumerated-lists

**Comment by newville** [comment]
@mcmtroffaes  Thanks!  I haven't looked into this in some time, but that seems to work, now using Sphinx 1.6.3 and sphinxcontrib_bibtex-0.3.6 (from pip install).

But I'm seeing other behavior that I don't understand: using `:list: enumerated` seems to have exactly the opposite effect from what I would expect:  Having `:list: enumerated` renders HTML output like

```

[Author2016]  A. B. Author and ....
[BAuthor2017]  B. Author....

```

whereas not having  `:list: enumerated` renders

```
[1] A. B. Author and ....
[2]  B. Author....

```

so something still seems a little weird.  Anyway, I'll happily start trying it out in larger projects.
