### ISSUE TITLE
duplicate bibitems

### ISSUE THREAD

**Issue by thorade** [mcmtroffaes/sphinxcontrib-bibtex#99]
Using Sphinx 1.4.1 with sphinxcontrib-bibtex 0.3.3 on Windows 10 to produce a PDF, every bibitem in the tex file exists two times. Or rather, the full bibliography exists twice. 
Not sure whether this is a bug or if I am doing something wrong.
When compiling the same project on Linux, I get the same behavior.

Is the following issue related?
https://github.com/sphinx-doc/sphinx/issues/2412

**Comment by mcmtroffaes** [comment]
The latexpdf writer of sphinx has always been quite buggy, but I've never seen double bibliographies. Does this only happen with 1.4.1, or does it also happen with older versions of Sphinx?

**Comment by thorade** [comment]
Also older versions, on windows I have tried Sphinx 1.4 and 1.4.1,
on Xubuntu I am using Sphinx 1.3.3
But it is also possible that our Sphinx conf.py is buggy.

**Comment by thorade** [comment]
Does sphinxcontrib-bibtex have an example text that I can compile (to latex/pdf)?

**Comment by mcmtroffaes** [comment]
Thanks for the quick response. Yes, there's a simple one here: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/tree/develop/test/sphinx Does that work as expected for you?

**Comment by mcmtroffaes** [comment]
I've just tested this myself with sphinx 1.4.1 and the bibliography looks as I'd expect. So it must be some issue with your source. If you have it somewhere, happy to have a look.

**Comment by thorade** [comment]
That test works as expected, so it is a problem with my setup. 
My source is online at bitbucket, in a private repository that I cannot share.
Thanks for your time!

**Comment by mcmtroffaes** [comment]
You're welcome. Good luck tracking down the problem!
